/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type IssueFiltersAPI interface {

	/*
	CreateSavedFilter Create a saved filter for your organization

	This endpoint allows you to create a saved filter for your organization.

This endpoint requires a **Premium** subscription.


	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiCreateSavedFilterRequest
	*/
	CreateSavedFilter(ctx context.Context) ApiCreateSavedFilterRequest

	// CreateSavedFilterExecute executes the request
	//  @return ListSavedFilters200ResponseInner
	CreateSavedFilterExecute(r ApiCreateSavedFilterRequest) (*ListSavedFilters200ResponseInner, *http.Response, error)

	/*
	DeleteSavedFilter Delete a saved filter by ID

	Delete a saved filter by ID. The filter must be owned by the user's organization.


	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param filterId The ID of the saved filter.
	@return ApiDeleteSavedFilterRequest
	*/
	DeleteSavedFilter(ctx context.Context, filterId int32) ApiDeleteSavedFilterRequest

	// DeleteSavedFilterExecute executes the request
	DeleteSavedFilterExecute(r ApiDeleteSavedFilterRequest) (*http.Response, error)

	/*
	GetSavedFilterById Get a saved filter by ID

	Get a saved filter by ID. The filter must be owned by the user's organization.


	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param filterId The ID of the saved filter.
	@return ApiGetSavedFilterByIdRequest
	*/
	GetSavedFilterById(ctx context.Context, filterId int32) ApiGetSavedFilterByIdRequest

	// GetSavedFilterByIdExecute executes the request
	//  @return ListSavedFilters200ResponseInner
	GetSavedFilterByIdExecute(r ApiGetSavedFilterByIdRequest) (*ListSavedFilters200ResponseInner, *http.Response, error)

	/*
	ListSavedFilters List out saved filters

	This endpoint returns a list of saved filters for the organization. The filters are categorized into licensing, vulnerability, and quality -- only the requested category of filters will be returned.


	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiListSavedFiltersRequest
	*/
	ListSavedFilters(ctx context.Context) ApiListSavedFiltersRequest

	// ListSavedFiltersExecute executes the request
	//  @return []ListSavedFilters200ResponseInner
	ListSavedFiltersExecute(r ApiListSavedFiltersRequest) ([]ListSavedFilters200ResponseInner, *http.Response, error)

	/*
	UpdateSavedFilter Update a saved filter for your organization

	Update a saved filter for your organization. The filter must be owned by the user's organization.

This endpoint requires a **Premium** subscription.


	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param filterId The ID of the saved filter.
	@return ApiUpdateSavedFilterRequest
	*/
	UpdateSavedFilter(ctx context.Context, filterId int32) ApiUpdateSavedFilterRequest

	// UpdateSavedFilterExecute executes the request
	//  @return ListSavedFilters200ResponseInner
	UpdateSavedFilterExecute(r ApiUpdateSavedFilterRequest) (*ListSavedFilters200ResponseInner, *http.Response, error)
}

// IssueFiltersAPIService IssueFiltersAPI service
type IssueFiltersAPIService service

type ApiCreateSavedFilterRequest struct {
	ctx context.Context
	ApiService IssueFiltersAPI
	createSavedFilterRequest *CreateSavedFilterRequest
}

func (r ApiCreateSavedFilterRequest) CreateSavedFilterRequest(createSavedFilterRequest CreateSavedFilterRequest) ApiCreateSavedFilterRequest {
	r.createSavedFilterRequest = &createSavedFilterRequest
	return r
}

func (r ApiCreateSavedFilterRequest) Execute() (*ListSavedFilters200ResponseInner, *http.Response, error) {
	return r.ApiService.CreateSavedFilterExecute(r)
}

/*
CreateSavedFilter Create a saved filter for your organization

This endpoint allows you to create a saved filter for your organization.

This endpoint requires a **Premium** subscription.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCreateSavedFilterRequest
*/
func (a *IssueFiltersAPIService) CreateSavedFilter(ctx context.Context) ApiCreateSavedFilterRequest {
	return ApiCreateSavedFilterRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ListSavedFilters200ResponseInner
func (a *IssueFiltersAPIService) CreateSavedFilterExecute(r ApiCreateSavedFilterRequest) (*ListSavedFilters200ResponseInner, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ListSavedFilters200ResponseInner
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "IssueFiltersAPIService.CreateSavedFilter")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/issue-filters"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createSavedFilterRequest == nil {
		return localVarReturnValue, nil, reportError("createSavedFilterRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createSavedFilterRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDeleteSavedFilterRequest struct {
	ctx context.Context
	ApiService IssueFiltersAPI
	filterId int32
}

func (r ApiDeleteSavedFilterRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteSavedFilterExecute(r)
}

/*
DeleteSavedFilter Delete a saved filter by ID

Delete a saved filter by ID. The filter must be owned by the user's organization.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param filterId The ID of the saved filter.
 @return ApiDeleteSavedFilterRequest
*/
func (a *IssueFiltersAPIService) DeleteSavedFilter(ctx context.Context, filterId int32) ApiDeleteSavedFilterRequest {
	return ApiDeleteSavedFilterRequest{
		ApiService: a,
		ctx: ctx,
		filterId: filterId,
	}
}

// Execute executes the request
func (a *IssueFiltersAPIService) DeleteSavedFilterExecute(r ApiDeleteSavedFilterRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "IssueFiltersAPIService.DeleteSavedFilter")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/issue-filters/{filterId}"
	localVarPath = strings.Replace(localVarPath, "{"+"filterId"+"}", url.PathEscape(parameterValueToString(r.filterId, "filterId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v AddLicenseConclusion400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetSavedFilterByIdRequest struct {
	ctx context.Context
	ApiService IssueFiltersAPI
	filterId int32
}

func (r ApiGetSavedFilterByIdRequest) Execute() (*ListSavedFilters200ResponseInner, *http.Response, error) {
	return r.ApiService.GetSavedFilterByIdExecute(r)
}

/*
GetSavedFilterById Get a saved filter by ID

Get a saved filter by ID. The filter must be owned by the user's organization.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param filterId The ID of the saved filter.
 @return ApiGetSavedFilterByIdRequest
*/
func (a *IssueFiltersAPIService) GetSavedFilterById(ctx context.Context, filterId int32) ApiGetSavedFilterByIdRequest {
	return ApiGetSavedFilterByIdRequest{
		ApiService: a,
		ctx: ctx,
		filterId: filterId,
	}
}

// Execute executes the request
//  @return ListSavedFilters200ResponseInner
func (a *IssueFiltersAPIService) GetSavedFilterByIdExecute(r ApiGetSavedFilterByIdRequest) (*ListSavedFilters200ResponseInner, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ListSavedFilters200ResponseInner
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "IssueFiltersAPIService.GetSavedFilterById")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/issue-filters/{filterId}"
	localVarPath = strings.Replace(localVarPath, "{"+"filterId"+"}", url.PathEscape(parameterValueToString(r.filterId, "filterId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v AddLicenseConclusion400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListSavedFiltersRequest struct {
	ctx context.Context
	ApiService IssueFiltersAPI
	category *string
}

// The category of the issue filters.
func (r ApiListSavedFiltersRequest) Category(category string) ApiListSavedFiltersRequest {
	r.category = &category
	return r
}

func (r ApiListSavedFiltersRequest) Execute() ([]ListSavedFilters200ResponseInner, *http.Response, error) {
	return r.ApiService.ListSavedFiltersExecute(r)
}

/*
ListSavedFilters List out saved filters

This endpoint returns a list of saved filters for the organization. The filters are categorized into licensing, vulnerability, and quality -- only the requested category of filters will be returned.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiListSavedFiltersRequest
*/
func (a *IssueFiltersAPIService) ListSavedFilters(ctx context.Context) ApiListSavedFiltersRequest {
	return ApiListSavedFiltersRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []ListSavedFilters200ResponseInner
func (a *IssueFiltersAPIService) ListSavedFiltersExecute(r ApiListSavedFiltersRequest) ([]ListSavedFilters200ResponseInner, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []ListSavedFilters200ResponseInner
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "IssueFiltersAPIService.ListSavedFilters")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/issue-filters"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.category == nil {
		return localVarReturnValue, nil, reportError("category is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "category", r.category, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v AddLicenseConclusion400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateSavedFilterRequest struct {
	ctx context.Context
	ApiService IssueFiltersAPI
	filterId int32
	updateSavedFilterRequest *UpdateSavedFilterRequest
}

func (r ApiUpdateSavedFilterRequest) UpdateSavedFilterRequest(updateSavedFilterRequest UpdateSavedFilterRequest) ApiUpdateSavedFilterRequest {
	r.updateSavedFilterRequest = &updateSavedFilterRequest
	return r
}

func (r ApiUpdateSavedFilterRequest) Execute() (*ListSavedFilters200ResponseInner, *http.Response, error) {
	return r.ApiService.UpdateSavedFilterExecute(r)
}

/*
UpdateSavedFilter Update a saved filter for your organization

Update a saved filter for your organization. The filter must be owned by the user's organization.

This endpoint requires a **Premium** subscription.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param filterId The ID of the saved filter.
 @return ApiUpdateSavedFilterRequest
*/
func (a *IssueFiltersAPIService) UpdateSavedFilter(ctx context.Context, filterId int32) ApiUpdateSavedFilterRequest {
	return ApiUpdateSavedFilterRequest{
		ApiService: a,
		ctx: ctx,
		filterId: filterId,
	}
}

// Execute executes the request
//  @return ListSavedFilters200ResponseInner
func (a *IssueFiltersAPIService) UpdateSavedFilterExecute(r ApiUpdateSavedFilterRequest) (*ListSavedFilters200ResponseInner, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ListSavedFilters200ResponseInner
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "IssueFiltersAPIService.UpdateSavedFilter")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/issue-filters/{filterId}"
	localVarPath = strings.Replace(localVarPath, "{"+"filterId"+"}", url.PathEscape(parameterValueToString(r.filterId, "filterId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.updateSavedFilterRequest == nil {
		return localVarReturnValue, nil, reportError("updateSavedFilterRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.updateSavedFilterRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v AddLicenseConclusion400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
