/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the AddLicenseConclusion400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddLicenseConclusion400Response{}

// AddLicenseConclusion400Response struct for AddLicenseConclusion400Response
type AddLicenseConclusion400Response struct {
	// Unique identifier associated with the error
	Uuid *string `json:"uuid,omitempty"`
	// fossa specific error code
	Code *int32 `json:"code,omitempty"`
	// message associated with this error
	Message *string `json:"message,omitempty"`
	// name of the error
	Name *string `json:"name,omitempty"`
	// http status code number
	HttpStatusCode *int32 `json:"httpStatusCode,omitempty"`
}

// NewAddLicenseConclusion400Response instantiates a new AddLicenseConclusion400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddLicenseConclusion400Response() *AddLicenseConclusion400Response {
	this := AddLicenseConclusion400Response{}
	return &this
}

// NewAddLicenseConclusion400ResponseWithDefaults instantiates a new AddLicenseConclusion400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddLicenseConclusion400ResponseWithDefaults() *AddLicenseConclusion400Response {
	this := AddLicenseConclusion400Response{}
	return &this
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *AddLicenseConclusion400Response) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddLicenseConclusion400Response) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *AddLicenseConclusion400Response) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *AddLicenseConclusion400Response) SetUuid(v string) {
	o.Uuid = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *AddLicenseConclusion400Response) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddLicenseConclusion400Response) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *AddLicenseConclusion400Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *AddLicenseConclusion400Response) SetCode(v int32) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *AddLicenseConclusion400Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddLicenseConclusion400Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *AddLicenseConclusion400Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *AddLicenseConclusion400Response) SetMessage(v string) {
	o.Message = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AddLicenseConclusion400Response) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddLicenseConclusion400Response) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AddLicenseConclusion400Response) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AddLicenseConclusion400Response) SetName(v string) {
	o.Name = &v
}

// GetHttpStatusCode returns the HttpStatusCode field value if set, zero value otherwise.
func (o *AddLicenseConclusion400Response) GetHttpStatusCode() int32 {
	if o == nil || IsNil(o.HttpStatusCode) {
		var ret int32
		return ret
	}
	return *o.HttpStatusCode
}

// GetHttpStatusCodeOk returns a tuple with the HttpStatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddLicenseConclusion400Response) GetHttpStatusCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.HttpStatusCode) {
		return nil, false
	}
	return o.HttpStatusCode, true
}

// HasHttpStatusCode returns a boolean if a field has been set.
func (o *AddLicenseConclusion400Response) HasHttpStatusCode() bool {
	if o != nil && !IsNil(o.HttpStatusCode) {
		return true
	}

	return false
}

// SetHttpStatusCode gets a reference to the given int32 and assigns it to the HttpStatusCode field.
func (o *AddLicenseConclusion400Response) SetHttpStatusCode(v int32) {
	o.HttpStatusCode = &v
}

func (o AddLicenseConclusion400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddLicenseConclusion400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.HttpStatusCode) {
		toSerialize["httpStatusCode"] = o.HttpStatusCode
	}
	return toSerialize, nil
}

type NullableAddLicenseConclusion400Response struct {
	value *AddLicenseConclusion400Response
	isSet bool
}

func (v NullableAddLicenseConclusion400Response) Get() *AddLicenseConclusion400Response {
	return v.value
}

func (v *NullableAddLicenseConclusion400Response) Set(val *AddLicenseConclusion400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAddLicenseConclusion400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAddLicenseConclusion400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddLicenseConclusion400Response(val *AddLicenseConclusion400Response) *NullableAddLicenseConclusion400Response {
	return &NullableAddLicenseConclusion400Response{value: val, isSet: true}
}

func (v NullableAddLicenseConclusion400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddLicenseConclusion400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


