/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// DeleteReleaseGroupsIdsParameter - struct for DeleteReleaseGroupsIdsParameter
type DeleteReleaseGroupsIdsParameter struct {
	ArrayOfInt32 *[]int32
	String *string
}

// []int32AsDeleteReleaseGroupsIdsParameter is a convenience function that returns []int32 wrapped in DeleteReleaseGroupsIdsParameter
func ArrayOfInt32AsDeleteReleaseGroupsIdsParameter(v *[]int32) DeleteReleaseGroupsIdsParameter {
	return DeleteReleaseGroupsIdsParameter{
		ArrayOfInt32: v,
	}
}

// stringAsDeleteReleaseGroupsIdsParameter is a convenience function that returns string wrapped in DeleteReleaseGroupsIdsParameter
func StringAsDeleteReleaseGroupsIdsParameter(v *string) DeleteReleaseGroupsIdsParameter {
	return DeleteReleaseGroupsIdsParameter{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *DeleteReleaseGroupsIdsParameter) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ArrayOfInt32
	err = newStrictDecoder(data).Decode(&dst.ArrayOfInt32)
	if err == nil {
		jsonArrayOfInt32, _ := json.Marshal(dst.ArrayOfInt32)
		if string(jsonArrayOfInt32) == "{}" { // empty struct
			dst.ArrayOfInt32 = nil
		} else {
			if err = validator.Validate(dst.ArrayOfInt32); err != nil {
				dst.ArrayOfInt32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfInt32 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ArrayOfInt32 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(DeleteReleaseGroupsIdsParameter)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(DeleteReleaseGroupsIdsParameter): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(DeleteReleaseGroupsIdsParameter)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src DeleteReleaseGroupsIdsParameter) MarshalJSON() ([]byte, error) {
	if src.ArrayOfInt32 != nil {
		return json.Marshal(&src.ArrayOfInt32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *DeleteReleaseGroupsIdsParameter) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ArrayOfInt32 != nil {
		return obj.ArrayOfInt32
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj DeleteReleaseGroupsIdsParameter) GetActualInstanceValue() (interface{}) {
	if obj.ArrayOfInt32 != nil {
		return *obj.ArrayOfInt32
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableDeleteReleaseGroupsIdsParameter struct {
	value *DeleteReleaseGroupsIdsParameter
	isSet bool
}

func (v NullableDeleteReleaseGroupsIdsParameter) Get() *DeleteReleaseGroupsIdsParameter {
	return v.value
}

func (v *NullableDeleteReleaseGroupsIdsParameter) Set(val *DeleteReleaseGroupsIdsParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteReleaseGroupsIdsParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteReleaseGroupsIdsParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteReleaseGroupsIdsParameter(val *DeleteReleaseGroupsIdsParameter) *NullableDeleteReleaseGroupsIdsParameter {
	return &NullableDeleteReleaseGroupsIdsParameter{value: val, isSet: true}
}

func (v NullableDeleteReleaseGroupsIdsParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteReleaseGroupsIdsParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


