/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the GetReleaseGroups200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetReleaseGroups200Response{}

// GetReleaseGroups200Response struct for GetReleaseGroups200Response
type GetReleaseGroups200Response struct {
	Total *int32 `json:"total,omitempty"`
	ReleaseGroups []GetReleaseGroups200ResponseReleaseGroupsInner `json:"releaseGroups,omitempty"`
}

// NewGetReleaseGroups200Response instantiates a new GetReleaseGroups200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetReleaseGroups200Response() *GetReleaseGroups200Response {
	this := GetReleaseGroups200Response{}
	return &this
}

// NewGetReleaseGroups200ResponseWithDefaults instantiates a new GetReleaseGroups200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetReleaseGroups200ResponseWithDefaults() *GetReleaseGroups200Response {
	this := GetReleaseGroups200Response{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetReleaseGroups200Response) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReleaseGroups200Response) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetReleaseGroups200Response) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *GetReleaseGroups200Response) SetTotal(v int32) {
	o.Total = &v
}

// GetReleaseGroups returns the ReleaseGroups field value if set, zero value otherwise.
func (o *GetReleaseGroups200Response) GetReleaseGroups() []GetReleaseGroups200ResponseReleaseGroupsInner {
	if o == nil || IsNil(o.ReleaseGroups) {
		var ret []GetReleaseGroups200ResponseReleaseGroupsInner
		return ret
	}
	return o.ReleaseGroups
}

// GetReleaseGroupsOk returns a tuple with the ReleaseGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReleaseGroups200Response) GetReleaseGroupsOk() ([]GetReleaseGroups200ResponseReleaseGroupsInner, bool) {
	if o == nil || IsNil(o.ReleaseGroups) {
		return nil, false
	}
	return o.ReleaseGroups, true
}

// HasReleaseGroups returns a boolean if a field has been set.
func (o *GetReleaseGroups200Response) HasReleaseGroups() bool {
	if o != nil && !IsNil(o.ReleaseGroups) {
		return true
	}

	return false
}

// SetReleaseGroups gets a reference to the given []GetReleaseGroups200ResponseReleaseGroupsInner and assigns it to the ReleaseGroups field.
func (o *GetReleaseGroups200Response) SetReleaseGroups(v []GetReleaseGroups200ResponseReleaseGroupsInner) {
	o.ReleaseGroups = v
}

func (o GetReleaseGroups200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetReleaseGroups200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.ReleaseGroups) {
		toSerialize["releaseGroups"] = o.ReleaseGroups
	}
	return toSerialize, nil
}

type NullableGetReleaseGroups200Response struct {
	value *GetReleaseGroups200Response
	isSet bool
}

func (v NullableGetReleaseGroups200Response) Get() *GetReleaseGroups200Response {
	return v.value
}

func (v *NullableGetReleaseGroups200Response) Set(val *GetReleaseGroups200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetReleaseGroups200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetReleaseGroups200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetReleaseGroups200Response(val *GetReleaseGroups200Response) *NullableGetReleaseGroups200Response {
	return &NullableGetReleaseGroups200Response{value: val, isSet: true}
}

func (v NullableGetReleaseGroups200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetReleaseGroups200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


