/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the GetRevisionDependencies200ResponseInnerProject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRevisionDependencies200ResponseInnerProject{}

// GetRevisionDependencies200ResponseInnerProject Project metadata for the dependency
type GetRevisionDependencies200ResponseInnerProject struct {
	Locator *string `json:"locator,omitempty"`
	Title *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Url *string `json:"url,omitempty"`
	Authors []string `json:"authors,omitempty"`
}

// NewGetRevisionDependencies200ResponseInnerProject instantiates a new GetRevisionDependencies200ResponseInnerProject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRevisionDependencies200ResponseInnerProject() *GetRevisionDependencies200ResponseInnerProject {
	this := GetRevisionDependencies200ResponseInnerProject{}
	return &this
}

// NewGetRevisionDependencies200ResponseInnerProjectWithDefaults instantiates a new GetRevisionDependencies200ResponseInnerProject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRevisionDependencies200ResponseInnerProjectWithDefaults() *GetRevisionDependencies200ResponseInnerProject {
	this := GetRevisionDependencies200ResponseInnerProject{}
	return &this
}

// GetLocator returns the Locator field value if set, zero value otherwise.
func (o *GetRevisionDependencies200ResponseInnerProject) GetLocator() string {
	if o == nil || IsNil(o.Locator) {
		var ret string
		return ret
	}
	return *o.Locator
}

// GetLocatorOk returns a tuple with the Locator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionDependencies200ResponseInnerProject) GetLocatorOk() (*string, bool) {
	if o == nil || IsNil(o.Locator) {
		return nil, false
	}
	return o.Locator, true
}

// HasLocator returns a boolean if a field has been set.
func (o *GetRevisionDependencies200ResponseInnerProject) HasLocator() bool {
	if o != nil && !IsNil(o.Locator) {
		return true
	}

	return false
}

// SetLocator gets a reference to the given string and assigns it to the Locator field.
func (o *GetRevisionDependencies200ResponseInnerProject) SetLocator(v string) {
	o.Locator = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *GetRevisionDependencies200ResponseInnerProject) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionDependencies200ResponseInnerProject) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *GetRevisionDependencies200ResponseInnerProject) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *GetRevisionDependencies200ResponseInnerProject) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GetRevisionDependencies200ResponseInnerProject) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionDependencies200ResponseInnerProject) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GetRevisionDependencies200ResponseInnerProject) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GetRevisionDependencies200ResponseInnerProject) SetDescription(v string) {
	o.Description = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *GetRevisionDependencies200ResponseInnerProject) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionDependencies200ResponseInnerProject) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *GetRevisionDependencies200ResponseInnerProject) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *GetRevisionDependencies200ResponseInnerProject) SetUrl(v string) {
	o.Url = &v
}

// GetAuthors returns the Authors field value if set, zero value otherwise.
func (o *GetRevisionDependencies200ResponseInnerProject) GetAuthors() []string {
	if o == nil || IsNil(o.Authors) {
		var ret []string
		return ret
	}
	return o.Authors
}

// GetAuthorsOk returns a tuple with the Authors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionDependencies200ResponseInnerProject) GetAuthorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Authors) {
		return nil, false
	}
	return o.Authors, true
}

// HasAuthors returns a boolean if a field has been set.
func (o *GetRevisionDependencies200ResponseInnerProject) HasAuthors() bool {
	if o != nil && !IsNil(o.Authors) {
		return true
	}

	return false
}

// SetAuthors gets a reference to the given []string and assigns it to the Authors field.
func (o *GetRevisionDependencies200ResponseInnerProject) SetAuthors(v []string) {
	o.Authors = v
}

func (o GetRevisionDependencies200ResponseInnerProject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRevisionDependencies200ResponseInnerProject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Locator) {
		toSerialize["locator"] = o.Locator
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Authors) {
		toSerialize["authors"] = o.Authors
	}
	return toSerialize, nil
}

type NullableGetRevisionDependencies200ResponseInnerProject struct {
	value *GetRevisionDependencies200ResponseInnerProject
	isSet bool
}

func (v NullableGetRevisionDependencies200ResponseInnerProject) Get() *GetRevisionDependencies200ResponseInnerProject {
	return v.value
}

func (v *NullableGetRevisionDependencies200ResponseInnerProject) Set(val *GetRevisionDependencies200ResponseInnerProject) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRevisionDependencies200ResponseInnerProject) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRevisionDependencies200ResponseInnerProject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRevisionDependencies200ResponseInnerProject(val *GetRevisionDependencies200ResponseInnerProject) *NullableGetRevisionDependencies200ResponseInnerProject {
	return &NullableGetRevisionDependencies200ResponseInnerProject{value: val, isSet: true}
}

func (v NullableGetRevisionDependencies200ResponseInnerProject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRevisionDependencies200ResponseInnerProject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


