/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the PutOrganizationPipSettingsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PutOrganizationPipSettingsRequest{}

// PutOrganizationPipSettingsRequest struct for PutOrganizationPipSettingsRequest
type PutOrganizationPipSettingsRequest struct {
	// List of configured Pip Repositories
	Repositories []GetOrganizationPipSettings200ResponseRepositoriesInner `json:"repositories,omitempty"`
}

// NewPutOrganizationPipSettingsRequest instantiates a new PutOrganizationPipSettingsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutOrganizationPipSettingsRequest() *PutOrganizationPipSettingsRequest {
	this := PutOrganizationPipSettingsRequest{}
	return &this
}

// NewPutOrganizationPipSettingsRequestWithDefaults instantiates a new PutOrganizationPipSettingsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutOrganizationPipSettingsRequestWithDefaults() *PutOrganizationPipSettingsRequest {
	this := PutOrganizationPipSettingsRequest{}
	return &this
}

// GetRepositories returns the Repositories field value if set, zero value otherwise.
func (o *PutOrganizationPipSettingsRequest) GetRepositories() []GetOrganizationPipSettings200ResponseRepositoriesInner {
	if o == nil || IsNil(o.Repositories) {
		var ret []GetOrganizationPipSettings200ResponseRepositoriesInner
		return ret
	}
	return o.Repositories
}

// GetRepositoriesOk returns a tuple with the Repositories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutOrganizationPipSettingsRequest) GetRepositoriesOk() ([]GetOrganizationPipSettings200ResponseRepositoriesInner, bool) {
	if o == nil || IsNil(o.Repositories) {
		return nil, false
	}
	return o.Repositories, true
}

// HasRepositories returns a boolean if a field has been set.
func (o *PutOrganizationPipSettingsRequest) HasRepositories() bool {
	if o != nil && !IsNil(o.Repositories) {
		return true
	}

	return false
}

// SetRepositories gets a reference to the given []GetOrganizationPipSettings200ResponseRepositoriesInner and assigns it to the Repositories field.
func (o *PutOrganizationPipSettingsRequest) SetRepositories(v []GetOrganizationPipSettings200ResponseRepositoriesInner) {
	o.Repositories = v
}

func (o PutOrganizationPipSettingsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PutOrganizationPipSettingsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Repositories) {
		toSerialize["repositories"] = o.Repositories
	}
	return toSerialize, nil
}

type NullablePutOrganizationPipSettingsRequest struct {
	value *PutOrganizationPipSettingsRequest
	isSet bool
}

func (v NullablePutOrganizationPipSettingsRequest) Get() *PutOrganizationPipSettingsRequest {
	return v.value
}

func (v *NullablePutOrganizationPipSettingsRequest) Set(val *PutOrganizationPipSettingsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePutOrganizationPipSettingsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePutOrganizationPipSettingsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutOrganizationPipSettingsRequest(val *PutOrganizationPipSettingsRequest) *NullablePutOrganizationPipSettingsRequest {
	return &NullablePutOrganizationPipSettingsRequest{value: val, isSet: true}
}

func (v NullablePutOrganizationPipSettingsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutOrganizationPipSettingsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


