/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the GemServer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GemServer{}

// GemServer struct for GemServer
type GemServer struct {
	// UUID of the gem server (For FOSSA internal usage)
	Id *float32 `json:"_id,omitempty"`
	// URL of the external gem server
	Url *string `json:"url,omitempty"`
	// Username for authenticating to the gem server
	Username *string `json:"username,omitempty"`
	Password *GetOrganizationBowerSettings200ResponseRegistriesInnerUrl `json:"password,omitempty"`
	// Used when an existing password is obfuscated in the response
	PasswordPresent *bool `json:"PasswordPresent,omitempty"`
}

// NewGemServer instantiates a new GemServer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGemServer() *GemServer {
	this := GemServer{}
	return &this
}

// NewGemServerWithDefaults instantiates a new GemServer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGemServerWithDefaults() *GemServer {
	this := GemServer{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GemServer) GetId() float32 {
	if o == nil || IsNil(o.Id) {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GemServer) GetIdOk() (*float32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GemServer) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *GemServer) SetId(v float32) {
	o.Id = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *GemServer) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GemServer) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *GemServer) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *GemServer) SetUrl(v string) {
	o.Url = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *GemServer) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GemServer) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *GemServer) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *GemServer) SetUsername(v string) {
	o.Username = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *GemServer) GetPassword() GetOrganizationBowerSettings200ResponseRegistriesInnerUrl {
	if o == nil || IsNil(o.Password) {
		var ret GetOrganizationBowerSettings200ResponseRegistriesInnerUrl
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GemServer) GetPasswordOk() (*GetOrganizationBowerSettings200ResponseRegistriesInnerUrl, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *GemServer) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given GetOrganizationBowerSettings200ResponseRegistriesInnerUrl and assigns it to the Password field.
func (o *GemServer) SetPassword(v GetOrganizationBowerSettings200ResponseRegistriesInnerUrl) {
	o.Password = &v
}

// GetPasswordPresent returns the PasswordPresent field value if set, zero value otherwise.
func (o *GemServer) GetPasswordPresent() bool {
	if o == nil || IsNil(o.PasswordPresent) {
		var ret bool
		return ret
	}
	return *o.PasswordPresent
}

// GetPasswordPresentOk returns a tuple with the PasswordPresent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GemServer) GetPasswordPresentOk() (*bool, bool) {
	if o == nil || IsNil(o.PasswordPresent) {
		return nil, false
	}
	return o.PasswordPresent, true
}

// HasPasswordPresent returns a boolean if a field has been set.
func (o *GemServer) HasPasswordPresent() bool {
	if o != nil && !IsNil(o.PasswordPresent) {
		return true
	}

	return false
}

// SetPasswordPresent gets a reference to the given bool and assigns it to the PasswordPresent field.
func (o *GemServer) SetPasswordPresent(v bool) {
	o.PasswordPresent = &v
}

func (o GemServer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GemServer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["_id"] = o.Id
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.PasswordPresent) {
		toSerialize["PasswordPresent"] = o.PasswordPresent
	}
	return toSerialize, nil
}

type NullableGemServer struct {
	value *GemServer
	isSet bool
}

func (v NullableGemServer) Get() *GemServer {
	return v.value
}

func (v *NullableGemServer) Set(val *GemServer) {
	v.value = val
	v.isSet = true
}

func (v NullableGemServer) IsSet() bool {
	return v.isSet
}

func (v *NullableGemServer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGemServer(val *GemServer) *NullableGemServer {
	return &NullableGemServer{value: val, isSet: true}
}

func (v NullableGemServer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGemServer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


