/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
	"time"
)

// checks if the GetReleaseGroupReleaseScans200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetReleaseGroupReleaseScans200ResponseInner{}

// GetReleaseGroupReleaseScans200ResponseInner struct for GetReleaseGroupReleaseScans200ResponseInner
type GetReleaseGroupReleaseScans200ResponseInner struct {
	Id *int32 `json:"id,omitempty"`
	ScannedAt *time.Time `json:"scanned_at,omitempty"`
	OrganizationId *int32 `json:"organizationId,omitempty"`
	ProjectGroupReleaseId *int32 `json:"projectGroupReleaseId,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	RevisionScans []GetReleaseGroupReleaseScans200ResponseInnerRevisionScansInner `json:"revisionScans,omitempty"`
}

// NewGetReleaseGroupReleaseScans200ResponseInner instantiates a new GetReleaseGroupReleaseScans200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetReleaseGroupReleaseScans200ResponseInner() *GetReleaseGroupReleaseScans200ResponseInner {
	this := GetReleaseGroupReleaseScans200ResponseInner{}
	return &this
}

// NewGetReleaseGroupReleaseScans200ResponseInnerWithDefaults instantiates a new GetReleaseGroupReleaseScans200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetReleaseGroupReleaseScans200ResponseInnerWithDefaults() *GetReleaseGroupReleaseScans200ResponseInner {
	this := GetReleaseGroupReleaseScans200ResponseInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetReleaseGroupReleaseScans200ResponseInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReleaseGroupReleaseScans200ResponseInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetReleaseGroupReleaseScans200ResponseInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetReleaseGroupReleaseScans200ResponseInner) SetId(v int32) {
	o.Id = &v
}

// GetScannedAt returns the ScannedAt field value if set, zero value otherwise.
func (o *GetReleaseGroupReleaseScans200ResponseInner) GetScannedAt() time.Time {
	if o == nil || IsNil(o.ScannedAt) {
		var ret time.Time
		return ret
	}
	return *o.ScannedAt
}

// GetScannedAtOk returns a tuple with the ScannedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReleaseGroupReleaseScans200ResponseInner) GetScannedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ScannedAt) {
		return nil, false
	}
	return o.ScannedAt, true
}

// HasScannedAt returns a boolean if a field has been set.
func (o *GetReleaseGroupReleaseScans200ResponseInner) HasScannedAt() bool {
	if o != nil && !IsNil(o.ScannedAt) {
		return true
	}

	return false
}

// SetScannedAt gets a reference to the given time.Time and assigns it to the ScannedAt field.
func (o *GetReleaseGroupReleaseScans200ResponseInner) SetScannedAt(v time.Time) {
	o.ScannedAt = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *GetReleaseGroupReleaseScans200ResponseInner) GetOrganizationId() int32 {
	if o == nil || IsNil(o.OrganizationId) {
		var ret int32
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReleaseGroupReleaseScans200ResponseInner) GetOrganizationIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *GetReleaseGroupReleaseScans200ResponseInner) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given int32 and assigns it to the OrganizationId field.
func (o *GetReleaseGroupReleaseScans200ResponseInner) SetOrganizationId(v int32) {
	o.OrganizationId = &v
}

// GetProjectGroupReleaseId returns the ProjectGroupReleaseId field value if set, zero value otherwise.
func (o *GetReleaseGroupReleaseScans200ResponseInner) GetProjectGroupReleaseId() int32 {
	if o == nil || IsNil(o.ProjectGroupReleaseId) {
		var ret int32
		return ret
	}
	return *o.ProjectGroupReleaseId
}

// GetProjectGroupReleaseIdOk returns a tuple with the ProjectGroupReleaseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReleaseGroupReleaseScans200ResponseInner) GetProjectGroupReleaseIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProjectGroupReleaseId) {
		return nil, false
	}
	return o.ProjectGroupReleaseId, true
}

// HasProjectGroupReleaseId returns a boolean if a field has been set.
func (o *GetReleaseGroupReleaseScans200ResponseInner) HasProjectGroupReleaseId() bool {
	if o != nil && !IsNil(o.ProjectGroupReleaseId) {
		return true
	}

	return false
}

// SetProjectGroupReleaseId gets a reference to the given int32 and assigns it to the ProjectGroupReleaseId field.
func (o *GetReleaseGroupReleaseScans200ResponseInner) SetProjectGroupReleaseId(v int32) {
	o.ProjectGroupReleaseId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetReleaseGroupReleaseScans200ResponseInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReleaseGroupReleaseScans200ResponseInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetReleaseGroupReleaseScans200ResponseInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *GetReleaseGroupReleaseScans200ResponseInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GetReleaseGroupReleaseScans200ResponseInner) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReleaseGroupReleaseScans200ResponseInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetReleaseGroupReleaseScans200ResponseInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *GetReleaseGroupReleaseScans200ResponseInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetRevisionScans returns the RevisionScans field value if set, zero value otherwise.
func (o *GetReleaseGroupReleaseScans200ResponseInner) GetRevisionScans() []GetReleaseGroupReleaseScans200ResponseInnerRevisionScansInner {
	if o == nil || IsNil(o.RevisionScans) {
		var ret []GetReleaseGroupReleaseScans200ResponseInnerRevisionScansInner
		return ret
	}
	return o.RevisionScans
}

// GetRevisionScansOk returns a tuple with the RevisionScans field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReleaseGroupReleaseScans200ResponseInner) GetRevisionScansOk() ([]GetReleaseGroupReleaseScans200ResponseInnerRevisionScansInner, bool) {
	if o == nil || IsNil(o.RevisionScans) {
		return nil, false
	}
	return o.RevisionScans, true
}

// HasRevisionScans returns a boolean if a field has been set.
func (o *GetReleaseGroupReleaseScans200ResponseInner) HasRevisionScans() bool {
	if o != nil && !IsNil(o.RevisionScans) {
		return true
	}

	return false
}

// SetRevisionScans gets a reference to the given []GetReleaseGroupReleaseScans200ResponseInnerRevisionScansInner and assigns it to the RevisionScans field.
func (o *GetReleaseGroupReleaseScans200ResponseInner) SetRevisionScans(v []GetReleaseGroupReleaseScans200ResponseInnerRevisionScansInner) {
	o.RevisionScans = v
}

func (o GetReleaseGroupReleaseScans200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetReleaseGroupReleaseScans200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ScannedAt) {
		toSerialize["scanned_at"] = o.ScannedAt
	}
	if !IsNil(o.OrganizationId) {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if !IsNil(o.ProjectGroupReleaseId) {
		toSerialize["projectGroupReleaseId"] = o.ProjectGroupReleaseId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.RevisionScans) {
		toSerialize["revisionScans"] = o.RevisionScans
	}
	return toSerialize, nil
}

type NullableGetReleaseGroupReleaseScans200ResponseInner struct {
	value *GetReleaseGroupReleaseScans200ResponseInner
	isSet bool
}

func (v NullableGetReleaseGroupReleaseScans200ResponseInner) Get() *GetReleaseGroupReleaseScans200ResponseInner {
	return v.value
}

func (v *NullableGetReleaseGroupReleaseScans200ResponseInner) Set(val *GetReleaseGroupReleaseScans200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetReleaseGroupReleaseScans200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetReleaseGroupReleaseScans200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetReleaseGroupReleaseScans200ResponseInner(val *GetReleaseGroupReleaseScans200ResponseInner) *NullableGetReleaseGroupReleaseScans200ResponseInner {
	return &NullableGetReleaseGroupReleaseScans200ResponseInner{value: val, isSet: true}
}

func (v NullableGetReleaseGroupReleaseScans200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetReleaseGroupReleaseScans200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


