/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the GetRevisionComponentsPaths200ResponsePathsInnerOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRevisionComponentsPaths200ResponsePathsInnerOneOf1{}

// GetRevisionComponentsPaths200ResponsePathsInnerOneOf1 A file node with component revision and root project revision
type GetRevisionComponentsPaths200ResponsePathsInnerOneOf1 struct {
	// Type of component path node (directory or file)
	Type *string `json:"type,omitempty"`
	// Name of file
	Name *string `json:"name,omitempty"`
	// Path to file
	Path *string `json:"path,omitempty"`
	// Dependency revision matched in file
	RevisionId *string `json:"revisionId,omitempty"`
	// Component Id for dependency and file
	ComponentId *string `json:"componentId,omitempty"`
	// Package name of Dependency matched in file
	PackageName *string `json:"packageName,omitempty"`
	// Version of Dependency matched in file
	Version *string `json:"version,omitempty"`
	// Revision of root Binary Decomposition project
	RootProjectRevisionLocator *string `json:"rootProjectRevisionLocator,omitempty"`
}

// NewGetRevisionComponentsPaths200ResponsePathsInnerOneOf1 instantiates a new GetRevisionComponentsPaths200ResponsePathsInnerOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRevisionComponentsPaths200ResponsePathsInnerOneOf1() *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1 {
	this := GetRevisionComponentsPaths200ResponsePathsInnerOneOf1{}
	return &this
}

// NewGetRevisionComponentsPaths200ResponsePathsInnerOneOf1WithDefaults instantiates a new GetRevisionComponentsPaths200ResponsePathsInnerOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRevisionComponentsPaths200ResponsePathsInnerOneOf1WithDefaults() *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1 {
	this := GetRevisionComponentsPaths200ResponsePathsInnerOneOf1{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) SetType(v string) {
	o.Type = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) SetName(v string) {
	o.Name = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) SetPath(v string) {
	o.Path = &v
}

// GetRevisionId returns the RevisionId field value if set, zero value otherwise.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) GetRevisionId() string {
	if o == nil || IsNil(o.RevisionId) {
		var ret string
		return ret
	}
	return *o.RevisionId
}

// GetRevisionIdOk returns a tuple with the RevisionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) GetRevisionIdOk() (*string, bool) {
	if o == nil || IsNil(o.RevisionId) {
		return nil, false
	}
	return o.RevisionId, true
}

// HasRevisionId returns a boolean if a field has been set.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) HasRevisionId() bool {
	if o != nil && !IsNil(o.RevisionId) {
		return true
	}

	return false
}

// SetRevisionId gets a reference to the given string and assigns it to the RevisionId field.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) SetRevisionId(v string) {
	o.RevisionId = &v
}

// GetComponentId returns the ComponentId field value if set, zero value otherwise.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) GetComponentId() string {
	if o == nil || IsNil(o.ComponentId) {
		var ret string
		return ret
	}
	return *o.ComponentId
}

// GetComponentIdOk returns a tuple with the ComponentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) GetComponentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ComponentId) {
		return nil, false
	}
	return o.ComponentId, true
}

// HasComponentId returns a boolean if a field has been set.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) HasComponentId() bool {
	if o != nil && !IsNil(o.ComponentId) {
		return true
	}

	return false
}

// SetComponentId gets a reference to the given string and assigns it to the ComponentId field.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) SetComponentId(v string) {
	o.ComponentId = &v
}

// GetPackageName returns the PackageName field value if set, zero value otherwise.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) GetPackageName() string {
	if o == nil || IsNil(o.PackageName) {
		var ret string
		return ret
	}
	return *o.PackageName
}

// GetPackageNameOk returns a tuple with the PackageName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) GetPackageNameOk() (*string, bool) {
	if o == nil || IsNil(o.PackageName) {
		return nil, false
	}
	return o.PackageName, true
}

// HasPackageName returns a boolean if a field has been set.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) HasPackageName() bool {
	if o != nil && !IsNil(o.PackageName) {
		return true
	}

	return false
}

// SetPackageName gets a reference to the given string and assigns it to the PackageName field.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) SetPackageName(v string) {
	o.PackageName = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) SetVersion(v string) {
	o.Version = &v
}

// GetRootProjectRevisionLocator returns the RootProjectRevisionLocator field value if set, zero value otherwise.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) GetRootProjectRevisionLocator() string {
	if o == nil || IsNil(o.RootProjectRevisionLocator) {
		var ret string
		return ret
	}
	return *o.RootProjectRevisionLocator
}

// GetRootProjectRevisionLocatorOk returns a tuple with the RootProjectRevisionLocator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) GetRootProjectRevisionLocatorOk() (*string, bool) {
	if o == nil || IsNil(o.RootProjectRevisionLocator) {
		return nil, false
	}
	return o.RootProjectRevisionLocator, true
}

// HasRootProjectRevisionLocator returns a boolean if a field has been set.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) HasRootProjectRevisionLocator() bool {
	if o != nil && !IsNil(o.RootProjectRevisionLocator) {
		return true
	}

	return false
}

// SetRootProjectRevisionLocator gets a reference to the given string and assigns it to the RootProjectRevisionLocator field.
func (o *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) SetRootProjectRevisionLocator(v string) {
	o.RootProjectRevisionLocator = &v
}

func (o GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.RevisionId) {
		toSerialize["revisionId"] = o.RevisionId
	}
	if !IsNil(o.ComponentId) {
		toSerialize["componentId"] = o.ComponentId
	}
	if !IsNil(o.PackageName) {
		toSerialize["packageName"] = o.PackageName
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.RootProjectRevisionLocator) {
		toSerialize["rootProjectRevisionLocator"] = o.RootProjectRevisionLocator
	}
	return toSerialize, nil
}

type NullableGetRevisionComponentsPaths200ResponsePathsInnerOneOf1 struct {
	value *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1
	isSet bool
}

func (v NullableGetRevisionComponentsPaths200ResponsePathsInnerOneOf1) Get() *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1 {
	return v.value
}

func (v *NullableGetRevisionComponentsPaths200ResponsePathsInnerOneOf1) Set(val *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRevisionComponentsPaths200ResponsePathsInnerOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRevisionComponentsPaths200ResponsePathsInnerOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRevisionComponentsPaths200ResponsePathsInnerOneOf1(val *GetRevisionComponentsPaths200ResponsePathsInnerOneOf1) *NullableGetRevisionComponentsPaths200ResponsePathsInnerOneOf1 {
	return &NullableGetRevisionComponentsPaths200ResponsePathsInnerOneOf1{value: val, isSet: true}
}

func (v NullableGetRevisionComponentsPaths200ResponsePathsInnerOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRevisionComponentsPaths200ResponsePathsInnerOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


