/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the BowerRegistry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BowerRegistry{}

// BowerRegistry struct for BowerRegistry
type BowerRegistry struct {
	// UUID of the config (For FOSSA internal usage)
	Id *float32 `json:"_id,omitempty"`
	Url *GetOrganizationBowerSettings200ResponseRegistriesInnerUrl `json:"url,omitempty"`
	// Used when an existing URL is obfuscated in the response
	UrlPresent *bool `json:"UrlPresent,omitempty"`
}

// NewBowerRegistry instantiates a new BowerRegistry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBowerRegistry() *BowerRegistry {
	this := BowerRegistry{}
	return &this
}

// NewBowerRegistryWithDefaults instantiates a new BowerRegistry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBowerRegistryWithDefaults() *BowerRegistry {
	this := BowerRegistry{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BowerRegistry) GetId() float32 {
	if o == nil || IsNil(o.Id) {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BowerRegistry) GetIdOk() (*float32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BowerRegistry) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *BowerRegistry) SetId(v float32) {
	o.Id = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *BowerRegistry) GetUrl() GetOrganizationBowerSettings200ResponseRegistriesInnerUrl {
	if o == nil || IsNil(o.Url) {
		var ret GetOrganizationBowerSettings200ResponseRegistriesInnerUrl
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BowerRegistry) GetUrlOk() (*GetOrganizationBowerSettings200ResponseRegistriesInnerUrl, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *BowerRegistry) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given GetOrganizationBowerSettings200ResponseRegistriesInnerUrl and assigns it to the Url field.
func (o *BowerRegistry) SetUrl(v GetOrganizationBowerSettings200ResponseRegistriesInnerUrl) {
	o.Url = &v
}

// GetUrlPresent returns the UrlPresent field value if set, zero value otherwise.
func (o *BowerRegistry) GetUrlPresent() bool {
	if o == nil || IsNil(o.UrlPresent) {
		var ret bool
		return ret
	}
	return *o.UrlPresent
}

// GetUrlPresentOk returns a tuple with the UrlPresent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BowerRegistry) GetUrlPresentOk() (*bool, bool) {
	if o == nil || IsNil(o.UrlPresent) {
		return nil, false
	}
	return o.UrlPresent, true
}

// HasUrlPresent returns a boolean if a field has been set.
func (o *BowerRegistry) HasUrlPresent() bool {
	if o != nil && !IsNil(o.UrlPresent) {
		return true
	}

	return false
}

// SetUrlPresent gets a reference to the given bool and assigns it to the UrlPresent field.
func (o *BowerRegistry) SetUrlPresent(v bool) {
	o.UrlPresent = &v
}

func (o BowerRegistry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BowerRegistry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["_id"] = o.Id
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.UrlPresent) {
		toSerialize["UrlPresent"] = o.UrlPresent
	}
	return toSerialize, nil
}

type NullableBowerRegistry struct {
	value *BowerRegistry
	isSet bool
}

func (v NullableBowerRegistry) Get() *BowerRegistry {
	return v.value
}

func (v *NullableBowerRegistry) Set(val *BowerRegistry) {
	v.value = val
	v.isSet = true
}

func (v NullableBowerRegistry) IsSet() bool {
	return v.isSet
}

func (v *NullableBowerRegistry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBowerRegistry(val *BowerRegistry) *NullableBowerRegistry {
	return &NullableBowerRegistry{value: val, isSet: true}
}

func (v NullableBowerRegistry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBowerRegistry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


