/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the GetOrganizationBowerSettings200ResponseRegistriesInnerUrl type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrganizationBowerSettings200ResponseRegistriesInnerUrl{}

// GetOrganizationBowerSettings200ResponseRegistriesInnerUrl struct for GetOrganizationBowerSettings200ResponseRegistriesInnerUrl
type GetOrganizationBowerSettings200ResponseRegistriesInnerUrl struct {
	Type *string `json:"__type,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewGetOrganizationBowerSettings200ResponseRegistriesInnerUrl instantiates a new GetOrganizationBowerSettings200ResponseRegistriesInnerUrl object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrganizationBowerSettings200ResponseRegistriesInnerUrl() *GetOrganizationBowerSettings200ResponseRegistriesInnerUrl {
	this := GetOrganizationBowerSettings200ResponseRegistriesInnerUrl{}
	return &this
}

// NewGetOrganizationBowerSettings200ResponseRegistriesInnerUrlWithDefaults instantiates a new GetOrganizationBowerSettings200ResponseRegistriesInnerUrl object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrganizationBowerSettings200ResponseRegistriesInnerUrlWithDefaults() *GetOrganizationBowerSettings200ResponseRegistriesInnerUrl {
	this := GetOrganizationBowerSettings200ResponseRegistriesInnerUrl{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetOrganizationBowerSettings200ResponseRegistriesInnerUrl) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationBowerSettings200ResponseRegistriesInnerUrl) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetOrganizationBowerSettings200ResponseRegistriesInnerUrl) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetOrganizationBowerSettings200ResponseRegistriesInnerUrl) SetType(v string) {
	o.Type = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *GetOrganizationBowerSettings200ResponseRegistriesInnerUrl) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationBowerSettings200ResponseRegistriesInnerUrl) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *GetOrganizationBowerSettings200ResponseRegistriesInnerUrl) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *GetOrganizationBowerSettings200ResponseRegistriesInnerUrl) SetValue(v string) {
	o.Value = &v
}

func (o GetOrganizationBowerSettings200ResponseRegistriesInnerUrl) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrganizationBowerSettings200ResponseRegistriesInnerUrl) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["__type"] = o.Type
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableGetOrganizationBowerSettings200ResponseRegistriesInnerUrl struct {
	value *GetOrganizationBowerSettings200ResponseRegistriesInnerUrl
	isSet bool
}

func (v NullableGetOrganizationBowerSettings200ResponseRegistriesInnerUrl) Get() *GetOrganizationBowerSettings200ResponseRegistriesInnerUrl {
	return v.value
}

func (v *NullableGetOrganizationBowerSettings200ResponseRegistriesInnerUrl) Set(val *GetOrganizationBowerSettings200ResponseRegistriesInnerUrl) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrganizationBowerSettings200ResponseRegistriesInnerUrl) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrganizationBowerSettings200ResponseRegistriesInnerUrl) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrganizationBowerSettings200ResponseRegistriesInnerUrl(val *GetOrganizationBowerSettings200ResponseRegistriesInnerUrl) *NullableGetOrganizationBowerSettings200ResponseRegistriesInnerUrl {
	return &NullableGetOrganizationBowerSettings200ResponseRegistriesInnerUrl{value: val, isSet: true}
}

func (v NullableGetOrganizationBowerSettings200ResponseRegistriesInnerUrl) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrganizationBowerSettings200ResponseRegistriesInnerUrl) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


