/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddLicenseConclusionRequestScopeOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddLicenseConclusionRequestScopeOneOf{}

// AddLicenseConclusionRequestScopeOneOf struct for AddLicenseConclusionRequestScopeOneOf
type AddLicenseConclusionRequestScopeOneOf struct {
	// Project-scoped conclusion
	Scope string `json:"scope"`
	// The locator of the project
	ProjectLocator string `json:"projectLocator"`
}

type _AddLicenseConclusionRequestScopeOneOf AddLicenseConclusionRequestScopeOneOf

// NewAddLicenseConclusionRequestScopeOneOf instantiates a new AddLicenseConclusionRequestScopeOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddLicenseConclusionRequestScopeOneOf(scope string, projectLocator string) *AddLicenseConclusionRequestScopeOneOf {
	this := AddLicenseConclusionRequestScopeOneOf{}
	this.Scope = scope
	this.ProjectLocator = projectLocator
	return &this
}

// NewAddLicenseConclusionRequestScopeOneOfWithDefaults instantiates a new AddLicenseConclusionRequestScopeOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddLicenseConclusionRequestScopeOneOfWithDefaults() *AddLicenseConclusionRequestScopeOneOf {
	this := AddLicenseConclusionRequestScopeOneOf{}
	return &this
}

// GetScope returns the Scope field value
func (o *AddLicenseConclusionRequestScopeOneOf) GetScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *AddLicenseConclusionRequestScopeOneOf) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *AddLicenseConclusionRequestScopeOneOf) SetScope(v string) {
	o.Scope = v
}

// GetProjectLocator returns the ProjectLocator field value
func (o *AddLicenseConclusionRequestScopeOneOf) GetProjectLocator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectLocator
}

// GetProjectLocatorOk returns a tuple with the ProjectLocator field value
// and a boolean to check if the value has been set.
func (o *AddLicenseConclusionRequestScopeOneOf) GetProjectLocatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectLocator, true
}

// SetProjectLocator sets field value
func (o *AddLicenseConclusionRequestScopeOneOf) SetProjectLocator(v string) {
	o.ProjectLocator = v
}

func (o AddLicenseConclusionRequestScopeOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddLicenseConclusionRequestScopeOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["scope"] = o.Scope
	toSerialize["projectLocator"] = o.ProjectLocator
	return toSerialize, nil
}

func (o *AddLicenseConclusionRequestScopeOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"scope",
		"projectLocator",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddLicenseConclusionRequestScopeOneOf := _AddLicenseConclusionRequestScopeOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddLicenseConclusionRequestScopeOneOf)

	if err != nil {
		return err
	}

	*o = AddLicenseConclusionRequestScopeOneOf(varAddLicenseConclusionRequestScopeOneOf)

	return err
}

type NullableAddLicenseConclusionRequestScopeOneOf struct {
	value *AddLicenseConclusionRequestScopeOneOf
	isSet bool
}

func (v NullableAddLicenseConclusionRequestScopeOneOf) Get() *AddLicenseConclusionRequestScopeOneOf {
	return v.value
}

func (v *NullableAddLicenseConclusionRequestScopeOneOf) Set(val *AddLicenseConclusionRequestScopeOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAddLicenseConclusionRequestScopeOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAddLicenseConclusionRequestScopeOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddLicenseConclusionRequestScopeOneOf(val *AddLicenseConclusionRequestScopeOneOf) *NullableAddLicenseConclusionRequestScopeOneOf {
	return &NullableAddLicenseConclusionRequestScopeOneOf{value: val, isSet: true}
}

func (v NullableAddLicenseConclusionRequestScopeOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddLicenseConclusionRequestScopeOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


