/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the GetLicenseList200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetLicenseList200Response{}

// GetLicenseList200Response struct for GetLicenseList200Response
type GetLicenseList200Response struct {
	Data []string `json:"data,omitempty"`
}

// NewGetLicenseList200Response instantiates a new GetLicenseList200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLicenseList200Response() *GetLicenseList200Response {
	this := GetLicenseList200Response{}
	return &this
}

// NewGetLicenseList200ResponseWithDefaults instantiates a new GetLicenseList200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLicenseList200ResponseWithDefaults() *GetLicenseList200Response {
	this := GetLicenseList200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetLicenseList200Response) GetData() []string {
	if o == nil || IsNil(o.Data) {
		var ret []string
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLicenseList200Response) GetDataOk() ([]string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetLicenseList200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []string and assigns it to the Data field.
func (o *GetLicenseList200Response) SetData(v []string) {
	o.Data = v
}

func (o GetLicenseList200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetLicenseList200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGetLicenseList200Response struct {
	value *GetLicenseList200Response
	isSet bool
}

func (v NullableGetLicenseList200Response) Get() *GetLicenseList200Response {
	return v.value
}

func (v *NullableGetLicenseList200Response) Set(val *GetLicenseList200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLicenseList200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLicenseList200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLicenseList200Response(val *GetLicenseList200Response) *NullableGetLicenseList200Response {
	return &NullableGetLicenseList200Response{value: val, isSet: true}
}

func (v NullableGetLicenseList200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetLicenseList200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


