/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
	"time"
)

// checks if the GetAllUsers200ResponseInnerTokensInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAllUsers200ResponseInnerTokensInner{}

// GetAllUsers200ResponseInnerTokensInner struct for GetAllUsers200ResponseInnerTokensInner
type GetAllUsers200ResponseInnerTokensInner struct {
	// The token's unique identifier
	Id *int32 `json:"id,omitempty"`
	// The token's name
	Name *string `json:"name,omitempty"`
	IsDisabled *bool `json:"isDisabled,omitempty"`
	// The date the token was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// The date the token was created
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Meta *GetAllUsers200ResponseInnerTokensInnerMeta `json:"meta,omitempty"`
}

// NewGetAllUsers200ResponseInnerTokensInner instantiates a new GetAllUsers200ResponseInnerTokensInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAllUsers200ResponseInnerTokensInner() *GetAllUsers200ResponseInnerTokensInner {
	this := GetAllUsers200ResponseInnerTokensInner{}
	return &this
}

// NewGetAllUsers200ResponseInnerTokensInnerWithDefaults instantiates a new GetAllUsers200ResponseInnerTokensInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAllUsers200ResponseInnerTokensInnerWithDefaults() *GetAllUsers200ResponseInnerTokensInner {
	this := GetAllUsers200ResponseInnerTokensInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetAllUsers200ResponseInnerTokensInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllUsers200ResponseInnerTokensInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetAllUsers200ResponseInnerTokensInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetAllUsers200ResponseInnerTokensInner) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetAllUsers200ResponseInnerTokensInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllUsers200ResponseInnerTokensInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetAllUsers200ResponseInnerTokensInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetAllUsers200ResponseInnerTokensInner) SetName(v string) {
	o.Name = &v
}

// GetIsDisabled returns the IsDisabled field value if set, zero value otherwise.
func (o *GetAllUsers200ResponseInnerTokensInner) GetIsDisabled() bool {
	if o == nil || IsNil(o.IsDisabled) {
		var ret bool
		return ret
	}
	return *o.IsDisabled
}

// GetIsDisabledOk returns a tuple with the IsDisabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllUsers200ResponseInnerTokensInner) GetIsDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDisabled) {
		return nil, false
	}
	return o.IsDisabled, true
}

// HasIsDisabled returns a boolean if a field has been set.
func (o *GetAllUsers200ResponseInnerTokensInner) HasIsDisabled() bool {
	if o != nil && !IsNil(o.IsDisabled) {
		return true
	}

	return false
}

// SetIsDisabled gets a reference to the given bool and assigns it to the IsDisabled field.
func (o *GetAllUsers200ResponseInnerTokensInner) SetIsDisabled(v bool) {
	o.IsDisabled = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GetAllUsers200ResponseInnerTokensInner) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllUsers200ResponseInnerTokensInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetAllUsers200ResponseInnerTokensInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *GetAllUsers200ResponseInnerTokensInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetAllUsers200ResponseInnerTokensInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllUsers200ResponseInnerTokensInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetAllUsers200ResponseInnerTokensInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *GetAllUsers200ResponseInnerTokensInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *GetAllUsers200ResponseInnerTokensInner) GetMeta() GetAllUsers200ResponseInnerTokensInnerMeta {
	if o == nil || IsNil(o.Meta) {
		var ret GetAllUsers200ResponseInnerTokensInnerMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllUsers200ResponseInnerTokensInner) GetMetaOk() (*GetAllUsers200ResponseInnerTokensInnerMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *GetAllUsers200ResponseInnerTokensInner) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given GetAllUsers200ResponseInnerTokensInnerMeta and assigns it to the Meta field.
func (o *GetAllUsers200ResponseInnerTokensInner) SetMeta(v GetAllUsers200ResponseInnerTokensInnerMeta) {
	o.Meta = &v
}

func (o GetAllUsers200ResponseInnerTokensInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAllUsers200ResponseInnerTokensInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.IsDisabled) {
		toSerialize["isDisabled"] = o.IsDisabled
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableGetAllUsers200ResponseInnerTokensInner struct {
	value *GetAllUsers200ResponseInnerTokensInner
	isSet bool
}

func (v NullableGetAllUsers200ResponseInnerTokensInner) Get() *GetAllUsers200ResponseInnerTokensInner {
	return v.value
}

func (v *NullableGetAllUsers200ResponseInnerTokensInner) Set(val *GetAllUsers200ResponseInnerTokensInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAllUsers200ResponseInnerTokensInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAllUsers200ResponseInnerTokensInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAllUsers200ResponseInnerTokensInner(val *GetAllUsers200ResponseInnerTokensInner) *NullableGetAllUsers200ResponseInnerTokensInner {
	return &NullableGetAllUsers200ResponseInnerTokensInner{value: val, isSet: true}
}

func (v NullableGetAllUsers200ResponseInnerTokensInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAllUsers200ResponseInnerTokensInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


