/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped{}

// GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped struct for GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped
type GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped struct {
	// Filter by one or more team IDs. Providing \"null\" will return all unassigned projects.
	Licenses []string `json:"licenses,omitempty"`
	LastEditedBy *string `json:"lastEditedBy,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

// NewGetProjectDependencies200ResponseDependenciesInnerConclusionsScoped instantiates a new GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProjectDependencies200ResponseDependenciesInnerConclusionsScoped() *GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped {
	this := GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped{}
	return &this
}

// NewGetProjectDependencies200ResponseDependenciesInnerConclusionsScopedWithDefaults instantiates a new GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProjectDependencies200ResponseDependenciesInnerConclusionsScopedWithDefaults() *GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped {
	this := GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped{}
	return &this
}

// GetLicenses returns the Licenses field value if set, zero value otherwise.
func (o *GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) GetLicenses() []string {
	if o == nil || IsNil(o.Licenses) {
		var ret []string
		return ret
	}
	return o.Licenses
}

// GetLicensesOk returns a tuple with the Licenses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) GetLicensesOk() ([]string, bool) {
	if o == nil || IsNil(o.Licenses) {
		return nil, false
	}
	return o.Licenses, true
}

// HasLicenses returns a boolean if a field has been set.
func (o *GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) HasLicenses() bool {
	if o != nil && !IsNil(o.Licenses) {
		return true
	}

	return false
}

// SetLicenses gets a reference to the given []string and assigns it to the Licenses field.
func (o *GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) SetLicenses(v []string) {
	o.Licenses = v
}

// GetLastEditedBy returns the LastEditedBy field value if set, zero value otherwise.
func (o *GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) GetLastEditedBy() string {
	if o == nil || IsNil(o.LastEditedBy) {
		var ret string
		return ret
	}
	return *o.LastEditedBy
}

// GetLastEditedByOk returns a tuple with the LastEditedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) GetLastEditedByOk() (*string, bool) {
	if o == nil || IsNil(o.LastEditedBy) {
		return nil, false
	}
	return o.LastEditedBy, true
}

// HasLastEditedBy returns a boolean if a field has been set.
func (o *GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) HasLastEditedBy() bool {
	if o != nil && !IsNil(o.LastEditedBy) {
		return true
	}

	return false
}

// SetLastEditedBy gets a reference to the given string and assigns it to the LastEditedBy field.
func (o *GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) SetLastEditedBy(v string) {
	o.LastEditedBy = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Licenses) {
		toSerialize["licenses"] = o.Licenses
	}
	if !IsNil(o.LastEditedBy) {
		toSerialize["lastEditedBy"] = o.LastEditedBy
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableGetProjectDependencies200ResponseDependenciesInnerConclusionsScoped struct {
	value *GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped
	isSet bool
}

func (v NullableGetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) Get() *GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped {
	return v.value
}

func (v *NullableGetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) Set(val *GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProjectDependencies200ResponseDependenciesInnerConclusionsScoped(val *GetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) *NullableGetProjectDependencies200ResponseDependenciesInnerConclusionsScoped {
	return &NullableGetProjectDependencies200ResponseDependenciesInnerConclusionsScoped{value: val, isSet: true}
}

func (v NullableGetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProjectDependencies200ResponseDependenciesInnerConclusionsScoped) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


