/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the CreateRevisionAttributionPublicReportV2202Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRevisionAttributionPublicReportV2202Response{}

// CreateRevisionAttributionPublicReportV2202Response struct for CreateRevisionAttributionPublicReportV2202Response
type CreateRevisionAttributionPublicReportV2202Response struct {
	Report *CreateRevisionAttributionPublicReportV2202ResponseReport `json:"report,omitempty"`
	Task *GetRevisionAttributionEmailV2200Response `json:"task,omitempty"`
}

// NewCreateRevisionAttributionPublicReportV2202Response instantiates a new CreateRevisionAttributionPublicReportV2202Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRevisionAttributionPublicReportV2202Response() *CreateRevisionAttributionPublicReportV2202Response {
	this := CreateRevisionAttributionPublicReportV2202Response{}
	return &this
}

// NewCreateRevisionAttributionPublicReportV2202ResponseWithDefaults instantiates a new CreateRevisionAttributionPublicReportV2202Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRevisionAttributionPublicReportV2202ResponseWithDefaults() *CreateRevisionAttributionPublicReportV2202Response {
	this := CreateRevisionAttributionPublicReportV2202Response{}
	return &this
}

// GetReport returns the Report field value if set, zero value otherwise.
func (o *CreateRevisionAttributionPublicReportV2202Response) GetReport() CreateRevisionAttributionPublicReportV2202ResponseReport {
	if o == nil || IsNil(o.Report) {
		var ret CreateRevisionAttributionPublicReportV2202ResponseReport
		return ret
	}
	return *o.Report
}

// GetReportOk returns a tuple with the Report field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRevisionAttributionPublicReportV2202Response) GetReportOk() (*CreateRevisionAttributionPublicReportV2202ResponseReport, bool) {
	if o == nil || IsNil(o.Report) {
		return nil, false
	}
	return o.Report, true
}

// HasReport returns a boolean if a field has been set.
func (o *CreateRevisionAttributionPublicReportV2202Response) HasReport() bool {
	if o != nil && !IsNil(o.Report) {
		return true
	}

	return false
}

// SetReport gets a reference to the given CreateRevisionAttributionPublicReportV2202ResponseReport and assigns it to the Report field.
func (o *CreateRevisionAttributionPublicReportV2202Response) SetReport(v CreateRevisionAttributionPublicReportV2202ResponseReport) {
	o.Report = &v
}

// GetTask returns the Task field value if set, zero value otherwise.
func (o *CreateRevisionAttributionPublicReportV2202Response) GetTask() GetRevisionAttributionEmailV2200Response {
	if o == nil || IsNil(o.Task) {
		var ret GetRevisionAttributionEmailV2200Response
		return ret
	}
	return *o.Task
}

// GetTaskOk returns a tuple with the Task field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRevisionAttributionPublicReportV2202Response) GetTaskOk() (*GetRevisionAttributionEmailV2200Response, bool) {
	if o == nil || IsNil(o.Task) {
		return nil, false
	}
	return o.Task, true
}

// HasTask returns a boolean if a field has been set.
func (o *CreateRevisionAttributionPublicReportV2202Response) HasTask() bool {
	if o != nil && !IsNil(o.Task) {
		return true
	}

	return false
}

// SetTask gets a reference to the given GetRevisionAttributionEmailV2200Response and assigns it to the Task field.
func (o *CreateRevisionAttributionPublicReportV2202Response) SetTask(v GetRevisionAttributionEmailV2200Response) {
	o.Task = &v
}

func (o CreateRevisionAttributionPublicReportV2202Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRevisionAttributionPublicReportV2202Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Report) {
		toSerialize["report"] = o.Report
	}
	if !IsNil(o.Task) {
		toSerialize["task"] = o.Task
	}
	return toSerialize, nil
}

type NullableCreateRevisionAttributionPublicReportV2202Response struct {
	value *CreateRevisionAttributionPublicReportV2202Response
	isSet bool
}

func (v NullableCreateRevisionAttributionPublicReportV2202Response) Get() *CreateRevisionAttributionPublicReportV2202Response {
	return v.value
}

func (v *NullableCreateRevisionAttributionPublicReportV2202Response) Set(val *CreateRevisionAttributionPublicReportV2202Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRevisionAttributionPublicReportV2202Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRevisionAttributionPublicReportV2202Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRevisionAttributionPublicReportV2202Response(val *CreateRevisionAttributionPublicReportV2202Response) *NullableCreateRevisionAttributionPublicReportV2202Response {
	return &NullableCreateRevisionAttributionPublicReportV2202Response{value: val, isSet: true}
}

func (v NullableCreateRevisionAttributionPublicReportV2202Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRevisionAttributionPublicReportV2202Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


