/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
	"time"
)

// checks if the GetReleaseGroups200ResponseReleaseGroupsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetReleaseGroups200ResponseReleaseGroupsInner{}

// GetReleaseGroups200ResponseReleaseGroupsInner struct for GetReleaseGroups200ResponseReleaseGroupsInner
type GetReleaseGroups200ResponseReleaseGroupsInner struct {
	Id *int32 `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
	PublicOnPortal *bool `json:"publicOnPortal,omitempty"`
	Scanned *time.Time `json:"scanned,omitempty"`
	Issues *int32 `json:"issues,omitempty"`
	Projects *int32 `json:"projects,omitempty"`
}

// NewGetReleaseGroups200ResponseReleaseGroupsInner instantiates a new GetReleaseGroups200ResponseReleaseGroupsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetReleaseGroups200ResponseReleaseGroupsInner() *GetReleaseGroups200ResponseReleaseGroupsInner {
	this := GetReleaseGroups200ResponseReleaseGroupsInner{}
	return &this
}

// NewGetReleaseGroups200ResponseReleaseGroupsInnerWithDefaults instantiates a new GetReleaseGroups200ResponseReleaseGroupsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetReleaseGroups200ResponseReleaseGroupsInnerWithDefaults() *GetReleaseGroups200ResponseReleaseGroupsInner {
	this := GetReleaseGroups200ResponseReleaseGroupsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) SetId(v int32) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) SetTitle(v string) {
	o.Title = &v
}

// GetPublicOnPortal returns the PublicOnPortal field value if set, zero value otherwise.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) GetPublicOnPortal() bool {
	if o == nil || IsNil(o.PublicOnPortal) {
		var ret bool
		return ret
	}
	return *o.PublicOnPortal
}

// GetPublicOnPortalOk returns a tuple with the PublicOnPortal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) GetPublicOnPortalOk() (*bool, bool) {
	if o == nil || IsNil(o.PublicOnPortal) {
		return nil, false
	}
	return o.PublicOnPortal, true
}

// HasPublicOnPortal returns a boolean if a field has been set.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) HasPublicOnPortal() bool {
	if o != nil && !IsNil(o.PublicOnPortal) {
		return true
	}

	return false
}

// SetPublicOnPortal gets a reference to the given bool and assigns it to the PublicOnPortal field.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) SetPublicOnPortal(v bool) {
	o.PublicOnPortal = &v
}

// GetScanned returns the Scanned field value if set, zero value otherwise.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) GetScanned() time.Time {
	if o == nil || IsNil(o.Scanned) {
		var ret time.Time
		return ret
	}
	return *o.Scanned
}

// GetScannedOk returns a tuple with the Scanned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) GetScannedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Scanned) {
		return nil, false
	}
	return o.Scanned, true
}

// HasScanned returns a boolean if a field has been set.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) HasScanned() bool {
	if o != nil && !IsNil(o.Scanned) {
		return true
	}

	return false
}

// SetScanned gets a reference to the given time.Time and assigns it to the Scanned field.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) SetScanned(v time.Time) {
	o.Scanned = &v
}

// GetIssues returns the Issues field value if set, zero value otherwise.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) GetIssues() int32 {
	if o == nil || IsNil(o.Issues) {
		var ret int32
		return ret
	}
	return *o.Issues
}

// GetIssuesOk returns a tuple with the Issues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) GetIssuesOk() (*int32, bool) {
	if o == nil || IsNil(o.Issues) {
		return nil, false
	}
	return o.Issues, true
}

// HasIssues returns a boolean if a field has been set.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) HasIssues() bool {
	if o != nil && !IsNil(o.Issues) {
		return true
	}

	return false
}

// SetIssues gets a reference to the given int32 and assigns it to the Issues field.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) SetIssues(v int32) {
	o.Issues = &v
}

// GetProjects returns the Projects field value if set, zero value otherwise.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) GetProjects() int32 {
	if o == nil || IsNil(o.Projects) {
		var ret int32
		return ret
	}
	return *o.Projects
}

// GetProjectsOk returns a tuple with the Projects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) GetProjectsOk() (*int32, bool) {
	if o == nil || IsNil(o.Projects) {
		return nil, false
	}
	return o.Projects, true
}

// HasProjects returns a boolean if a field has been set.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) HasProjects() bool {
	if o != nil && !IsNil(o.Projects) {
		return true
	}

	return false
}

// SetProjects gets a reference to the given int32 and assigns it to the Projects field.
func (o *GetReleaseGroups200ResponseReleaseGroupsInner) SetProjects(v int32) {
	o.Projects = &v
}

func (o GetReleaseGroups200ResponseReleaseGroupsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetReleaseGroups200ResponseReleaseGroupsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.PublicOnPortal) {
		toSerialize["publicOnPortal"] = o.PublicOnPortal
	}
	if !IsNil(o.Scanned) {
		toSerialize["scanned"] = o.Scanned
	}
	if !IsNil(o.Issues) {
		toSerialize["issues"] = o.Issues
	}
	if !IsNil(o.Projects) {
		toSerialize["projects"] = o.Projects
	}
	return toSerialize, nil
}

type NullableGetReleaseGroups200ResponseReleaseGroupsInner struct {
	value *GetReleaseGroups200ResponseReleaseGroupsInner
	isSet bool
}

func (v NullableGetReleaseGroups200ResponseReleaseGroupsInner) Get() *GetReleaseGroups200ResponseReleaseGroupsInner {
	return v.value
}

func (v *NullableGetReleaseGroups200ResponseReleaseGroupsInner) Set(val *GetReleaseGroups200ResponseReleaseGroupsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetReleaseGroups200ResponseReleaseGroupsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetReleaseGroups200ResponseReleaseGroupsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetReleaseGroups200ResponseReleaseGroupsInner(val *GetReleaseGroups200ResponseReleaseGroupsInner) *NullableGetReleaseGroups200ResponseReleaseGroupsInner {
	return &NullableGetReleaseGroups200ResponseReleaseGroupsInner{value: val, isSet: true}
}

func (v NullableGetReleaseGroups200ResponseReleaseGroupsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetReleaseGroups200ResponseReleaseGroupsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


