/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the DeleteIssueExceptionsRequestOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteIssueExceptionsRequestOneOf{}

// DeleteIssueExceptionsRequestOneOf struct for DeleteIssueExceptionsRequestOneOf
type DeleteIssueExceptionsRequestOneOf struct {
	Kind *string `json:"kind,omitempty"`
	Filters *DeleteIssueExceptionsRequestOneOfFilters `json:"filters,omitempty"`
}

// NewDeleteIssueExceptionsRequestOneOf instantiates a new DeleteIssueExceptionsRequestOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteIssueExceptionsRequestOneOf() *DeleteIssueExceptionsRequestOneOf {
	this := DeleteIssueExceptionsRequestOneOf{}
	return &this
}

// NewDeleteIssueExceptionsRequestOneOfWithDefaults instantiates a new DeleteIssueExceptionsRequestOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteIssueExceptionsRequestOneOfWithDefaults() *DeleteIssueExceptionsRequestOneOf {
	this := DeleteIssueExceptionsRequestOneOf{}
	return &this
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *DeleteIssueExceptionsRequestOneOf) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteIssueExceptionsRequestOneOf) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *DeleteIssueExceptionsRequestOneOf) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *DeleteIssueExceptionsRequestOneOf) SetKind(v string) {
	o.Kind = &v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *DeleteIssueExceptionsRequestOneOf) GetFilters() DeleteIssueExceptionsRequestOneOfFilters {
	if o == nil || IsNil(o.Filters) {
		var ret DeleteIssueExceptionsRequestOneOfFilters
		return ret
	}
	return *o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteIssueExceptionsRequestOneOf) GetFiltersOk() (*DeleteIssueExceptionsRequestOneOfFilters, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *DeleteIssueExceptionsRequestOneOf) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given DeleteIssueExceptionsRequestOneOfFilters and assigns it to the Filters field.
func (o *DeleteIssueExceptionsRequestOneOf) SetFilters(v DeleteIssueExceptionsRequestOneOfFilters) {
	o.Filters = &v
}

func (o DeleteIssueExceptionsRequestOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteIssueExceptionsRequestOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	return toSerialize, nil
}

type NullableDeleteIssueExceptionsRequestOneOf struct {
	value *DeleteIssueExceptionsRequestOneOf
	isSet bool
}

func (v NullableDeleteIssueExceptionsRequestOneOf) Get() *DeleteIssueExceptionsRequestOneOf {
	return v.value
}

func (v *NullableDeleteIssueExceptionsRequestOneOf) Set(val *DeleteIssueExceptionsRequestOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteIssueExceptionsRequestOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteIssueExceptionsRequestOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteIssueExceptionsRequestOneOf(val *DeleteIssueExceptionsRequestOneOf) *NullableDeleteIssueExceptionsRequestOneOf {
	return &NullableDeleteIssueExceptionsRequestOneOf{value: val, isSet: true}
}

func (v NullableDeleteIssueExceptionsRequestOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteIssueExceptionsRequestOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


