/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GenerateOrganizationScimToken200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenerateOrganizationScimToken200Response{}

// GenerateOrganizationScimToken200Response struct for GenerateOrganizationScimToken200Response
type GenerateOrganizationScimToken200Response struct {
	// The generated SCIM bearer token, for the identity provider to authenticate against the `/api/scim` endpoints. FOSSA stores only a hash of it, so this response is the only time it is ever returned — it cannot be retrieved again afterward.
	Token string `json:"token"`
}

type _GenerateOrganizationScimToken200Response GenerateOrganizationScimToken200Response

// NewGenerateOrganizationScimToken200Response instantiates a new GenerateOrganizationScimToken200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateOrganizationScimToken200Response(token string) *GenerateOrganizationScimToken200Response {
	this := GenerateOrganizationScimToken200Response{}
	this.Token = token
	return &this
}

// NewGenerateOrganizationScimToken200ResponseWithDefaults instantiates a new GenerateOrganizationScimToken200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateOrganizationScimToken200ResponseWithDefaults() *GenerateOrganizationScimToken200Response {
	this := GenerateOrganizationScimToken200Response{}
	return &this
}

// GetToken returns the Token field value
func (o *GenerateOrganizationScimToken200Response) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *GenerateOrganizationScimToken200Response) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *GenerateOrganizationScimToken200Response) SetToken(v string) {
	o.Token = v
}

func (o GenerateOrganizationScimToken200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenerateOrganizationScimToken200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

func (o *GenerateOrganizationScimToken200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGenerateOrganizationScimToken200Response := _GenerateOrganizationScimToken200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGenerateOrganizationScimToken200Response)

	if err != nil {
		return err
	}

	*o = GenerateOrganizationScimToken200Response(varGenerateOrganizationScimToken200Response)

	return err
}

type NullableGenerateOrganizationScimToken200Response struct {
	value *GenerateOrganizationScimToken200Response
	isSet bool
}

func (v NullableGenerateOrganizationScimToken200Response) Get() *GenerateOrganizationScimToken200Response {
	return v.value
}

func (v *NullableGenerateOrganizationScimToken200Response) Set(val *GenerateOrganizationScimToken200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateOrganizationScimToken200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateOrganizationScimToken200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateOrganizationScimToken200Response(val *GenerateOrganizationScimToken200Response) *NullableGenerateOrganizationScimToken200Response {
	return &NullableGenerateOrganizationScimToken200Response{value: val, isSet: true}
}

func (v NullableGenerateOrganizationScimToken200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateOrganizationScimToken200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


