/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the GetProjectExportIssues200ResponseQualityIssuesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetProjectExportIssues200ResponseQualityIssuesInner{}

// GetProjectExportIssues200ResponseQualityIssuesInner struct for GetProjectExportIssues200ResponseQualityIssuesInner
type GetProjectExportIssues200ResponseQualityIssuesInner struct {
	// The dependency that the issue is associated with. 
	Dependency *string `json:"Dependency,omitempty"`
	// The revision of the dependency that the issue is associated with. 
	Revision *string `json:"Revision,omitempty"`
	// The type of issue. 
	Type *string `json:"Type,omitempty"`
	// A link to the project in the FOSSA UI. 
	FOSSA_URL *string `json:"FOSSA URL,omitempty"`
	// The User Project that the issue is associated with. 
	AffectedProject *string `json:"Affected Project,omitempty"`
	// A description of the policy rule that triggered this issue (if available). 
	Details *string `json:"Details,omitempty"`
	// The depth(s) of the dependency in the dependency tree. 
	DependencyDepths *string `json:"Dependency Depths,omitempty"`
}

// NewGetProjectExportIssues200ResponseQualityIssuesInner instantiates a new GetProjectExportIssues200ResponseQualityIssuesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProjectExportIssues200ResponseQualityIssuesInner() *GetProjectExportIssues200ResponseQualityIssuesInner {
	this := GetProjectExportIssues200ResponseQualityIssuesInner{}
	return &this
}

// NewGetProjectExportIssues200ResponseQualityIssuesInnerWithDefaults instantiates a new GetProjectExportIssues200ResponseQualityIssuesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProjectExportIssues200ResponseQualityIssuesInnerWithDefaults() *GetProjectExportIssues200ResponseQualityIssuesInner {
	this := GetProjectExportIssues200ResponseQualityIssuesInner{}
	return &this
}

// GetDependency returns the Dependency field value if set, zero value otherwise.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) GetDependency() string {
	if o == nil || IsNil(o.Dependency) {
		var ret string
		return ret
	}
	return *o.Dependency
}

// GetDependencyOk returns a tuple with the Dependency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) GetDependencyOk() (*string, bool) {
	if o == nil || IsNil(o.Dependency) {
		return nil, false
	}
	return o.Dependency, true
}

// HasDependency returns a boolean if a field has been set.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) HasDependency() bool {
	if o != nil && !IsNil(o.Dependency) {
		return true
	}

	return false
}

// SetDependency gets a reference to the given string and assigns it to the Dependency field.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) SetDependency(v string) {
	o.Dependency = &v
}

// GetRevision returns the Revision field value if set, zero value otherwise.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) GetRevision() string {
	if o == nil || IsNil(o.Revision) {
		var ret string
		return ret
	}
	return *o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) GetRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.Revision) {
		return nil, false
	}
	return o.Revision, true
}

// HasRevision returns a boolean if a field has been set.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) HasRevision() bool {
	if o != nil && !IsNil(o.Revision) {
		return true
	}

	return false
}

// SetRevision gets a reference to the given string and assigns it to the Revision field.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) SetRevision(v string) {
	o.Revision = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) SetType(v string) {
	o.Type = &v
}

// GetFOSSA_URL returns the FOSSA_URL field value if set, zero value otherwise.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) GetFOSSA_URL() string {
	if o == nil || IsNil(o.FOSSA_URL) {
		var ret string
		return ret
	}
	return *o.FOSSA_URL
}

// GetFOSSA_URLOk returns a tuple with the FOSSA_URL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) GetFOSSA_URLOk() (*string, bool) {
	if o == nil || IsNil(o.FOSSA_URL) {
		return nil, false
	}
	return o.FOSSA_URL, true
}

// HasFOSSA_URL returns a boolean if a field has been set.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) HasFOSSA_URL() bool {
	if o != nil && !IsNil(o.FOSSA_URL) {
		return true
	}

	return false
}

// SetFOSSA_URL gets a reference to the given string and assigns it to the FOSSA_URL field.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) SetFOSSA_URL(v string) {
	o.FOSSA_URL = &v
}

// GetAffectedProject returns the AffectedProject field value if set, zero value otherwise.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) GetAffectedProject() string {
	if o == nil || IsNil(o.AffectedProject) {
		var ret string
		return ret
	}
	return *o.AffectedProject
}

// GetAffectedProjectOk returns a tuple with the AffectedProject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) GetAffectedProjectOk() (*string, bool) {
	if o == nil || IsNil(o.AffectedProject) {
		return nil, false
	}
	return o.AffectedProject, true
}

// HasAffectedProject returns a boolean if a field has been set.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) HasAffectedProject() bool {
	if o != nil && !IsNil(o.AffectedProject) {
		return true
	}

	return false
}

// SetAffectedProject gets a reference to the given string and assigns it to the AffectedProject field.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) SetAffectedProject(v string) {
	o.AffectedProject = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) GetDetails() string {
	if o == nil || IsNil(o.Details) {
		var ret string
		return ret
	}
	return *o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) GetDetailsOk() (*string, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given string and assigns it to the Details field.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) SetDetails(v string) {
	o.Details = &v
}

// GetDependencyDepths returns the DependencyDepths field value if set, zero value otherwise.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) GetDependencyDepths() string {
	if o == nil || IsNil(o.DependencyDepths) {
		var ret string
		return ret
	}
	return *o.DependencyDepths
}

// GetDependencyDepthsOk returns a tuple with the DependencyDepths field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) GetDependencyDepthsOk() (*string, bool) {
	if o == nil || IsNil(o.DependencyDepths) {
		return nil, false
	}
	return o.DependencyDepths, true
}

// HasDependencyDepths returns a boolean if a field has been set.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) HasDependencyDepths() bool {
	if o != nil && !IsNil(o.DependencyDepths) {
		return true
	}

	return false
}

// SetDependencyDepths gets a reference to the given string and assigns it to the DependencyDepths field.
func (o *GetProjectExportIssues200ResponseQualityIssuesInner) SetDependencyDepths(v string) {
	o.DependencyDepths = &v
}

func (o GetProjectExportIssues200ResponseQualityIssuesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetProjectExportIssues200ResponseQualityIssuesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dependency) {
		toSerialize["Dependency"] = o.Dependency
	}
	if !IsNil(o.Revision) {
		toSerialize["Revision"] = o.Revision
	}
	if !IsNil(o.Type) {
		toSerialize["Type"] = o.Type
	}
	if !IsNil(o.FOSSA_URL) {
		toSerialize["FOSSA URL"] = o.FOSSA_URL
	}
	if !IsNil(o.AffectedProject) {
		toSerialize["Affected Project"] = o.AffectedProject
	}
	if !IsNil(o.Details) {
		toSerialize["Details"] = o.Details
	}
	if !IsNil(o.DependencyDepths) {
		toSerialize["Dependency Depths"] = o.DependencyDepths
	}
	return toSerialize, nil
}

type NullableGetProjectExportIssues200ResponseQualityIssuesInner struct {
	value *GetProjectExportIssues200ResponseQualityIssuesInner
	isSet bool
}

func (v NullableGetProjectExportIssues200ResponseQualityIssuesInner) Get() *GetProjectExportIssues200ResponseQualityIssuesInner {
	return v.value
}

func (v *NullableGetProjectExportIssues200ResponseQualityIssuesInner) Set(val *GetProjectExportIssues200ResponseQualityIssuesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProjectExportIssues200ResponseQualityIssuesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProjectExportIssues200ResponseQualityIssuesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProjectExportIssues200ResponseQualityIssuesInner(val *GetProjectExportIssues200ResponseQualityIssuesInner) *NullableGetProjectExportIssues200ResponseQualityIssuesInner {
	return &NullableGetProjectExportIssues200ResponseQualityIssuesInner{value: val, isSet: true}
}

func (v NullableGetProjectExportIssues200ResponseQualityIssuesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProjectExportIssues200ResponseQualityIssuesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


