/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the GetIssuesByType200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetIssuesByType200Response{}

// GetIssuesByType200Response struct for GetIssuesByType200Response
type GetIssuesByType200Response struct {
	PolicyConflict *int32 `json:"policy_conflict,omitempty"`
	PolicyFlag *int32 `json:"policy_flag,omitempty"`
	UnlicensedDependency *int32 `json:"unlicensed_dependency,omitempty"`
	OutdatedDependency *int32 `json:"outdated_dependency,omitempty"`
	Vulnerability *int32 `json:"vulnerability,omitempty"`
}

// NewGetIssuesByType200Response instantiates a new GetIssuesByType200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIssuesByType200Response() *GetIssuesByType200Response {
	this := GetIssuesByType200Response{}
	return &this
}

// NewGetIssuesByType200ResponseWithDefaults instantiates a new GetIssuesByType200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIssuesByType200ResponseWithDefaults() *GetIssuesByType200Response {
	this := GetIssuesByType200Response{}
	return &this
}

// GetPolicyConflict returns the PolicyConflict field value if set, zero value otherwise.
func (o *GetIssuesByType200Response) GetPolicyConflict() int32 {
	if o == nil || IsNil(o.PolicyConflict) {
		var ret int32
		return ret
	}
	return *o.PolicyConflict
}

// GetPolicyConflictOk returns a tuple with the PolicyConflict field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssuesByType200Response) GetPolicyConflictOk() (*int32, bool) {
	if o == nil || IsNil(o.PolicyConflict) {
		return nil, false
	}
	return o.PolicyConflict, true
}

// HasPolicyConflict returns a boolean if a field has been set.
func (o *GetIssuesByType200Response) HasPolicyConflict() bool {
	if o != nil && !IsNil(o.PolicyConflict) {
		return true
	}

	return false
}

// SetPolicyConflict gets a reference to the given int32 and assigns it to the PolicyConflict field.
func (o *GetIssuesByType200Response) SetPolicyConflict(v int32) {
	o.PolicyConflict = &v
}

// GetPolicyFlag returns the PolicyFlag field value if set, zero value otherwise.
func (o *GetIssuesByType200Response) GetPolicyFlag() int32 {
	if o == nil || IsNil(o.PolicyFlag) {
		var ret int32
		return ret
	}
	return *o.PolicyFlag
}

// GetPolicyFlagOk returns a tuple with the PolicyFlag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssuesByType200Response) GetPolicyFlagOk() (*int32, bool) {
	if o == nil || IsNil(o.PolicyFlag) {
		return nil, false
	}
	return o.PolicyFlag, true
}

// HasPolicyFlag returns a boolean if a field has been set.
func (o *GetIssuesByType200Response) HasPolicyFlag() bool {
	if o != nil && !IsNil(o.PolicyFlag) {
		return true
	}

	return false
}

// SetPolicyFlag gets a reference to the given int32 and assigns it to the PolicyFlag field.
func (o *GetIssuesByType200Response) SetPolicyFlag(v int32) {
	o.PolicyFlag = &v
}

// GetUnlicensedDependency returns the UnlicensedDependency field value if set, zero value otherwise.
func (o *GetIssuesByType200Response) GetUnlicensedDependency() int32 {
	if o == nil || IsNil(o.UnlicensedDependency) {
		var ret int32
		return ret
	}
	return *o.UnlicensedDependency
}

// GetUnlicensedDependencyOk returns a tuple with the UnlicensedDependency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssuesByType200Response) GetUnlicensedDependencyOk() (*int32, bool) {
	if o == nil || IsNil(o.UnlicensedDependency) {
		return nil, false
	}
	return o.UnlicensedDependency, true
}

// HasUnlicensedDependency returns a boolean if a field has been set.
func (o *GetIssuesByType200Response) HasUnlicensedDependency() bool {
	if o != nil && !IsNil(o.UnlicensedDependency) {
		return true
	}

	return false
}

// SetUnlicensedDependency gets a reference to the given int32 and assigns it to the UnlicensedDependency field.
func (o *GetIssuesByType200Response) SetUnlicensedDependency(v int32) {
	o.UnlicensedDependency = &v
}

// GetOutdatedDependency returns the OutdatedDependency field value if set, zero value otherwise.
func (o *GetIssuesByType200Response) GetOutdatedDependency() int32 {
	if o == nil || IsNil(o.OutdatedDependency) {
		var ret int32
		return ret
	}
	return *o.OutdatedDependency
}

// GetOutdatedDependencyOk returns a tuple with the OutdatedDependency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssuesByType200Response) GetOutdatedDependencyOk() (*int32, bool) {
	if o == nil || IsNil(o.OutdatedDependency) {
		return nil, false
	}
	return o.OutdatedDependency, true
}

// HasOutdatedDependency returns a boolean if a field has been set.
func (o *GetIssuesByType200Response) HasOutdatedDependency() bool {
	if o != nil && !IsNil(o.OutdatedDependency) {
		return true
	}

	return false
}

// SetOutdatedDependency gets a reference to the given int32 and assigns it to the OutdatedDependency field.
func (o *GetIssuesByType200Response) SetOutdatedDependency(v int32) {
	o.OutdatedDependency = &v
}

// GetVulnerability returns the Vulnerability field value if set, zero value otherwise.
func (o *GetIssuesByType200Response) GetVulnerability() int32 {
	if o == nil || IsNil(o.Vulnerability) {
		var ret int32
		return ret
	}
	return *o.Vulnerability
}

// GetVulnerabilityOk returns a tuple with the Vulnerability field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssuesByType200Response) GetVulnerabilityOk() (*int32, bool) {
	if o == nil || IsNil(o.Vulnerability) {
		return nil, false
	}
	return o.Vulnerability, true
}

// HasVulnerability returns a boolean if a field has been set.
func (o *GetIssuesByType200Response) HasVulnerability() bool {
	if o != nil && !IsNil(o.Vulnerability) {
		return true
	}

	return false
}

// SetVulnerability gets a reference to the given int32 and assigns it to the Vulnerability field.
func (o *GetIssuesByType200Response) SetVulnerability(v int32) {
	o.Vulnerability = &v
}

func (o GetIssuesByType200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetIssuesByType200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PolicyConflict) {
		toSerialize["policy_conflict"] = o.PolicyConflict
	}
	if !IsNil(o.PolicyFlag) {
		toSerialize["policy_flag"] = o.PolicyFlag
	}
	if !IsNil(o.UnlicensedDependency) {
		toSerialize["unlicensed_dependency"] = o.UnlicensedDependency
	}
	if !IsNil(o.OutdatedDependency) {
		toSerialize["outdated_dependency"] = o.OutdatedDependency
	}
	if !IsNil(o.Vulnerability) {
		toSerialize["vulnerability"] = o.Vulnerability
	}
	return toSerialize, nil
}

type NullableGetIssuesByType200Response struct {
	value *GetIssuesByType200Response
	isSet bool
}

func (v NullableGetIssuesByType200Response) Get() *GetIssuesByType200Response {
	return v.value
}

func (v *NullableGetIssuesByType200Response) Set(val *GetIssuesByType200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIssuesByType200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIssuesByType200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIssuesByType200Response(val *GetIssuesByType200Response) *NullableGetIssuesByType200Response {
	return &NullableGetIssuesByType200Response{value: val, isSet: true}
}

func (v NullableGetIssuesByType200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIssuesByType200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


