/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the GetLinkedOrganizations200ResponseOrganizationsToShareWithInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetLinkedOrganizations200ResponseOrganizationsToShareWithInner{}

// GetLinkedOrganizations200ResponseOrganizationsToShareWithInner struct for GetLinkedOrganizations200ResponseOrganizationsToShareWithInner
type GetLinkedOrganizations200ResponseOrganizationsToShareWithInner struct {
	// The ID of the shared organization record
	SharedOrganizationId *int64 `json:"sharedOrganizationId,omitempty"`
	// The name of the origin organization
	OriginOrganizationName *string `json:"originOrganizationName,omitempty"`
	// The name of the receiving organization
	ReceivingOrganizationName *string `json:"receivingOrganizationName,omitempty"`
}

// NewGetLinkedOrganizations200ResponseOrganizationsToShareWithInner instantiates a new GetLinkedOrganizations200ResponseOrganizationsToShareWithInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLinkedOrganizations200ResponseOrganizationsToShareWithInner() *GetLinkedOrganizations200ResponseOrganizationsToShareWithInner {
	this := GetLinkedOrganizations200ResponseOrganizationsToShareWithInner{}
	return &this
}

// NewGetLinkedOrganizations200ResponseOrganizationsToShareWithInnerWithDefaults instantiates a new GetLinkedOrganizations200ResponseOrganizationsToShareWithInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLinkedOrganizations200ResponseOrganizationsToShareWithInnerWithDefaults() *GetLinkedOrganizations200ResponseOrganizationsToShareWithInner {
	this := GetLinkedOrganizations200ResponseOrganizationsToShareWithInner{}
	return &this
}

// GetSharedOrganizationId returns the SharedOrganizationId field value if set, zero value otherwise.
func (o *GetLinkedOrganizations200ResponseOrganizationsToShareWithInner) GetSharedOrganizationId() int64 {
	if o == nil || IsNil(o.SharedOrganizationId) {
		var ret int64
		return ret
	}
	return *o.SharedOrganizationId
}

// GetSharedOrganizationIdOk returns a tuple with the SharedOrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLinkedOrganizations200ResponseOrganizationsToShareWithInner) GetSharedOrganizationIdOk() (*int64, bool) {
	if o == nil || IsNil(o.SharedOrganizationId) {
		return nil, false
	}
	return o.SharedOrganizationId, true
}

// HasSharedOrganizationId returns a boolean if a field has been set.
func (o *GetLinkedOrganizations200ResponseOrganizationsToShareWithInner) HasSharedOrganizationId() bool {
	if o != nil && !IsNil(o.SharedOrganizationId) {
		return true
	}

	return false
}

// SetSharedOrganizationId gets a reference to the given int64 and assigns it to the SharedOrganizationId field.
func (o *GetLinkedOrganizations200ResponseOrganizationsToShareWithInner) SetSharedOrganizationId(v int64) {
	o.SharedOrganizationId = &v
}

// GetOriginOrganizationName returns the OriginOrganizationName field value if set, zero value otherwise.
func (o *GetLinkedOrganizations200ResponseOrganizationsToShareWithInner) GetOriginOrganizationName() string {
	if o == nil || IsNil(o.OriginOrganizationName) {
		var ret string
		return ret
	}
	return *o.OriginOrganizationName
}

// GetOriginOrganizationNameOk returns a tuple with the OriginOrganizationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLinkedOrganizations200ResponseOrganizationsToShareWithInner) GetOriginOrganizationNameOk() (*string, bool) {
	if o == nil || IsNil(o.OriginOrganizationName) {
		return nil, false
	}
	return o.OriginOrganizationName, true
}

// HasOriginOrganizationName returns a boolean if a field has been set.
func (o *GetLinkedOrganizations200ResponseOrganizationsToShareWithInner) HasOriginOrganizationName() bool {
	if o != nil && !IsNil(o.OriginOrganizationName) {
		return true
	}

	return false
}

// SetOriginOrganizationName gets a reference to the given string and assigns it to the OriginOrganizationName field.
func (o *GetLinkedOrganizations200ResponseOrganizationsToShareWithInner) SetOriginOrganizationName(v string) {
	o.OriginOrganizationName = &v
}

// GetReceivingOrganizationName returns the ReceivingOrganizationName field value if set, zero value otherwise.
func (o *GetLinkedOrganizations200ResponseOrganizationsToShareWithInner) GetReceivingOrganizationName() string {
	if o == nil || IsNil(o.ReceivingOrganizationName) {
		var ret string
		return ret
	}
	return *o.ReceivingOrganizationName
}

// GetReceivingOrganizationNameOk returns a tuple with the ReceivingOrganizationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLinkedOrganizations200ResponseOrganizationsToShareWithInner) GetReceivingOrganizationNameOk() (*string, bool) {
	if o == nil || IsNil(o.ReceivingOrganizationName) {
		return nil, false
	}
	return o.ReceivingOrganizationName, true
}

// HasReceivingOrganizationName returns a boolean if a field has been set.
func (o *GetLinkedOrganizations200ResponseOrganizationsToShareWithInner) HasReceivingOrganizationName() bool {
	if o != nil && !IsNil(o.ReceivingOrganizationName) {
		return true
	}

	return false
}

// SetReceivingOrganizationName gets a reference to the given string and assigns it to the ReceivingOrganizationName field.
func (o *GetLinkedOrganizations200ResponseOrganizationsToShareWithInner) SetReceivingOrganizationName(v string) {
	o.ReceivingOrganizationName = &v
}

func (o GetLinkedOrganizations200ResponseOrganizationsToShareWithInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetLinkedOrganizations200ResponseOrganizationsToShareWithInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SharedOrganizationId) {
		toSerialize["sharedOrganizationId"] = o.SharedOrganizationId
	}
	if !IsNil(o.OriginOrganizationName) {
		toSerialize["originOrganizationName"] = o.OriginOrganizationName
	}
	if !IsNil(o.ReceivingOrganizationName) {
		toSerialize["receivingOrganizationName"] = o.ReceivingOrganizationName
	}
	return toSerialize, nil
}

type NullableGetLinkedOrganizations200ResponseOrganizationsToShareWithInner struct {
	value *GetLinkedOrganizations200ResponseOrganizationsToShareWithInner
	isSet bool
}

func (v NullableGetLinkedOrganizations200ResponseOrganizationsToShareWithInner) Get() *GetLinkedOrganizations200ResponseOrganizationsToShareWithInner {
	return v.value
}

func (v *NullableGetLinkedOrganizations200ResponseOrganizationsToShareWithInner) Set(val *GetLinkedOrganizations200ResponseOrganizationsToShareWithInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLinkedOrganizations200ResponseOrganizationsToShareWithInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLinkedOrganizations200ResponseOrganizationsToShareWithInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLinkedOrganizations200ResponseOrganizationsToShareWithInner(val *GetLinkedOrganizations200ResponseOrganizationsToShareWithInner) *NullableGetLinkedOrganizations200ResponseOrganizationsToShareWithInner {
	return &NullableGetLinkedOrganizations200ResponseOrganizationsToShareWithInner{value: val, isSet: true}
}

func (v NullableGetLinkedOrganizations200ResponseOrganizationsToShareWithInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetLinkedOrganizations200ResponseOrganizationsToShareWithInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


