/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the Obligation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Obligation{}

// Obligation struct for Obligation
type Obligation struct {
	// The description of the obligation.
	Description *string `json:"description,omitempty"`
	// The license associated with the obligation.
	License *string `json:"license,omitempty"`
	// A dictionary where the key is the parent locator and the value is an array of locators in which the obligation was found.
	Revisions map[string][]string `json:"revisions,omitempty"`
}

// NewObligation instantiates a new Obligation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObligation() *Obligation {
	this := Obligation{}
	return &this
}

// NewObligationWithDefaults instantiates a new Obligation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObligationWithDefaults() *Obligation {
	this := Obligation{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Obligation) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Obligation) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Obligation) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Obligation) SetDescription(v string) {
	o.Description = &v
}

// GetLicense returns the License field value if set, zero value otherwise.
func (o *Obligation) GetLicense() string {
	if o == nil || IsNil(o.License) {
		var ret string
		return ret
	}
	return *o.License
}

// GetLicenseOk returns a tuple with the License field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Obligation) GetLicenseOk() (*string, bool) {
	if o == nil || IsNil(o.License) {
		return nil, false
	}
	return o.License, true
}

// HasLicense returns a boolean if a field has been set.
func (o *Obligation) HasLicense() bool {
	if o != nil && !IsNil(o.License) {
		return true
	}

	return false
}

// SetLicense gets a reference to the given string and assigns it to the License field.
func (o *Obligation) SetLicense(v string) {
	o.License = &v
}

// GetRevisions returns the Revisions field value if set, zero value otherwise.
func (o *Obligation) GetRevisions() map[string][]string {
	if o == nil || IsNil(o.Revisions) {
		var ret map[string][]string
		return ret
	}
	return o.Revisions
}

// GetRevisionsOk returns a tuple with the Revisions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Obligation) GetRevisionsOk() (map[string][]string, bool) {
	if o == nil || IsNil(o.Revisions) {
		return map[string][]string{}, false
	}
	return o.Revisions, true
}

// HasRevisions returns a boolean if a field has been set.
func (o *Obligation) HasRevisions() bool {
	if o != nil && !IsNil(o.Revisions) {
		return true
	}

	return false
}

// SetRevisions gets a reference to the given map[string][]string and assigns it to the Revisions field.
func (o *Obligation) SetRevisions(v map[string][]string) {
	o.Revisions = v
}

func (o Obligation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Obligation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.License) {
		toSerialize["license"] = o.License
	}
	if !IsNil(o.Revisions) {
		toSerialize["revisions"] = o.Revisions
	}
	return toSerialize, nil
}

type NullableObligation struct {
	value *Obligation
	isSet bool
}

func (v NullableObligation) Get() *Obligation {
	return v.value
}

func (v *NullableObligation) Set(val *Obligation) {
	v.value = val
	v.isSet = true
}

func (v NullableObligation) IsSet() bool {
	return v.isSet
}

func (v *NullableObligation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObligation(val *Obligation) *NullableObligation {
	return &NullableObligation{value: val, isSet: true}
}

func (v NullableObligation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObligation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


