/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetSnippetPackages200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSnippetPackages200Response{}

// GetSnippetPackages200Response struct for GetSnippetPackages200Response
type GetSnippetPackages200Response struct {
	// Array of snippet packages
	Results []GetSnippetPackages200ResponseResultsInner `json:"results"`
	// Total number of snippet packages matching the filter criteria
	TotalCount int32 `json:"totalCount"`
	// Current page number
	Page int32 `json:"page"`
	// Number of items requested per page
	PageSize int32 `json:"pageSize"`
}

type _GetSnippetPackages200Response GetSnippetPackages200Response

// NewGetSnippetPackages200Response instantiates a new GetSnippetPackages200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSnippetPackages200Response(results []GetSnippetPackages200ResponseResultsInner, totalCount int32, page int32, pageSize int32) *GetSnippetPackages200Response {
	this := GetSnippetPackages200Response{}
	this.Results = results
	this.TotalCount = totalCount
	this.Page = page
	this.PageSize = pageSize
	return &this
}

// NewGetSnippetPackages200ResponseWithDefaults instantiates a new GetSnippetPackages200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSnippetPackages200ResponseWithDefaults() *GetSnippetPackages200Response {
	this := GetSnippetPackages200Response{}
	return &this
}

// GetResults returns the Results field value
func (o *GetSnippetPackages200Response) GetResults() []GetSnippetPackages200ResponseResultsInner {
	if o == nil {
		var ret []GetSnippetPackages200ResponseResultsInner
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *GetSnippetPackages200Response) GetResultsOk() ([]GetSnippetPackages200ResponseResultsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *GetSnippetPackages200Response) SetResults(v []GetSnippetPackages200ResponseResultsInner) {
	o.Results = v
}

// GetTotalCount returns the TotalCount field value
func (o *GetSnippetPackages200Response) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *GetSnippetPackages200Response) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *GetSnippetPackages200Response) SetTotalCount(v int32) {
	o.TotalCount = v
}

// GetPage returns the Page field value
func (o *GetSnippetPackages200Response) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *GetSnippetPackages200Response) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *GetSnippetPackages200Response) SetPage(v int32) {
	o.Page = v
}

// GetPageSize returns the PageSize field value
func (o *GetSnippetPackages200Response) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *GetSnippetPackages200Response) GetPageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *GetSnippetPackages200Response) SetPageSize(v int32) {
	o.PageSize = v
}

func (o GetSnippetPackages200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSnippetPackages200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["results"] = o.Results
	toSerialize["totalCount"] = o.TotalCount
	toSerialize["page"] = o.Page
	toSerialize["pageSize"] = o.PageSize
	return toSerialize, nil
}

func (o *GetSnippetPackages200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"results",
		"totalCount",
		"page",
		"pageSize",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSnippetPackages200Response := _GetSnippetPackages200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetSnippetPackages200Response)

	if err != nil {
		return err
	}

	*o = GetSnippetPackages200Response(varGetSnippetPackages200Response)

	return err
}

type NullableGetSnippetPackages200Response struct {
	value *GetSnippetPackages200Response
	isSet bool
}

func (v NullableGetSnippetPackages200Response) Get() *GetSnippetPackages200Response {
	return v.value
}

func (v *NullableGetSnippetPackages200Response) Set(val *GetSnippetPackages200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSnippetPackages200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSnippetPackages200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSnippetPackages200Response(val *GetSnippetPackages200Response) *NullableGetSnippetPackages200Response {
	return &NullableGetSnippetPackages200Response{value: val, isSet: true}
}

func (v NullableGetSnippetPackages200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSnippetPackages200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


