/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
	"time"
)

// checks if the GetTeamByIdV2200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTeamByIdV2200Response{}

// GetTeamByIdV2200Response struct for GetTeamByIdV2200Response
type GetTeamByIdV2200Response struct {
	// The team's unique identifier
	Id *int32 `json:"id,omitempty"`
	// The organization's unique identifier
	OrganizationId *int32 `json:"organizationId,omitempty"`
	// The team's name
	Name *string `json:"name,omitempty"`
	// The default role's unique identifier
	DefaultRoleId *int32 `json:"defaultRoleId,omitempty"`
	// Whether the team auto-adds users
	AutoAddUsers *bool `json:"autoAddUsers,omitempty"`
	// The team's unique identifier
	UniqueIdentifier *string `json:"uniqueIdentifier,omitempty"`
	// The team's creation date
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// The team's last update date
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Whether it's a normal team or a Team Group.
	TeamType *string `json:"teamType,omitempty"`
	// The number of members in the team
	TeamMembersCount *int32 `json:"teamMembersCount,omitempty"`
	// The number of release groups associated with the team
	TeamReleaseGroupsCount *int32 `json:"teamReleaseGroupsCount,omitempty"`
	// The number of projects associated with the team
	TeamProjectsCount *int32 `json:"teamProjectsCount,omitempty"`
	// The number of OIDC providers that can be accessed by members of this team. Includes both org-scoped providers and team-scoped providers where the scopeId matches the team ID. This property is only returned if the user has permission to view OIDC providers. 
	TeamOIDCProvidersCount *int32 `json:"teamOIDCProvidersCount,omitempty"`
}

// NewGetTeamByIdV2200Response instantiates a new GetTeamByIdV2200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTeamByIdV2200Response() *GetTeamByIdV2200Response {
	this := GetTeamByIdV2200Response{}
	return &this
}

// NewGetTeamByIdV2200ResponseWithDefaults instantiates a new GetTeamByIdV2200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTeamByIdV2200ResponseWithDefaults() *GetTeamByIdV2200Response {
	this := GetTeamByIdV2200Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetTeamByIdV2200Response) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTeamByIdV2200Response) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetTeamByIdV2200Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetTeamByIdV2200Response) SetId(v int32) {
	o.Id = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *GetTeamByIdV2200Response) GetOrganizationId() int32 {
	if o == nil || IsNil(o.OrganizationId) {
		var ret int32
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTeamByIdV2200Response) GetOrganizationIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *GetTeamByIdV2200Response) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given int32 and assigns it to the OrganizationId field.
func (o *GetTeamByIdV2200Response) SetOrganizationId(v int32) {
	o.OrganizationId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetTeamByIdV2200Response) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTeamByIdV2200Response) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetTeamByIdV2200Response) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetTeamByIdV2200Response) SetName(v string) {
	o.Name = &v
}

// GetDefaultRoleId returns the DefaultRoleId field value if set, zero value otherwise.
func (o *GetTeamByIdV2200Response) GetDefaultRoleId() int32 {
	if o == nil || IsNil(o.DefaultRoleId) {
		var ret int32
		return ret
	}
	return *o.DefaultRoleId
}

// GetDefaultRoleIdOk returns a tuple with the DefaultRoleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTeamByIdV2200Response) GetDefaultRoleIdOk() (*int32, bool) {
	if o == nil || IsNil(o.DefaultRoleId) {
		return nil, false
	}
	return o.DefaultRoleId, true
}

// HasDefaultRoleId returns a boolean if a field has been set.
func (o *GetTeamByIdV2200Response) HasDefaultRoleId() bool {
	if o != nil && !IsNil(o.DefaultRoleId) {
		return true
	}

	return false
}

// SetDefaultRoleId gets a reference to the given int32 and assigns it to the DefaultRoleId field.
func (o *GetTeamByIdV2200Response) SetDefaultRoleId(v int32) {
	o.DefaultRoleId = &v
}

// GetAutoAddUsers returns the AutoAddUsers field value if set, zero value otherwise.
func (o *GetTeamByIdV2200Response) GetAutoAddUsers() bool {
	if o == nil || IsNil(o.AutoAddUsers) {
		var ret bool
		return ret
	}
	return *o.AutoAddUsers
}

// GetAutoAddUsersOk returns a tuple with the AutoAddUsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTeamByIdV2200Response) GetAutoAddUsersOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoAddUsers) {
		return nil, false
	}
	return o.AutoAddUsers, true
}

// HasAutoAddUsers returns a boolean if a field has been set.
func (o *GetTeamByIdV2200Response) HasAutoAddUsers() bool {
	if o != nil && !IsNil(o.AutoAddUsers) {
		return true
	}

	return false
}

// SetAutoAddUsers gets a reference to the given bool and assigns it to the AutoAddUsers field.
func (o *GetTeamByIdV2200Response) SetAutoAddUsers(v bool) {
	o.AutoAddUsers = &v
}

// GetUniqueIdentifier returns the UniqueIdentifier field value if set, zero value otherwise.
func (o *GetTeamByIdV2200Response) GetUniqueIdentifier() string {
	if o == nil || IsNil(o.UniqueIdentifier) {
		var ret string
		return ret
	}
	return *o.UniqueIdentifier
}

// GetUniqueIdentifierOk returns a tuple with the UniqueIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTeamByIdV2200Response) GetUniqueIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.UniqueIdentifier) {
		return nil, false
	}
	return o.UniqueIdentifier, true
}

// HasUniqueIdentifier returns a boolean if a field has been set.
func (o *GetTeamByIdV2200Response) HasUniqueIdentifier() bool {
	if o != nil && !IsNil(o.UniqueIdentifier) {
		return true
	}

	return false
}

// SetUniqueIdentifier gets a reference to the given string and assigns it to the UniqueIdentifier field.
func (o *GetTeamByIdV2200Response) SetUniqueIdentifier(v string) {
	o.UniqueIdentifier = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetTeamByIdV2200Response) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTeamByIdV2200Response) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetTeamByIdV2200Response) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *GetTeamByIdV2200Response) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GetTeamByIdV2200Response) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTeamByIdV2200Response) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetTeamByIdV2200Response) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *GetTeamByIdV2200Response) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetTeamType returns the TeamType field value if set, zero value otherwise.
func (o *GetTeamByIdV2200Response) GetTeamType() string {
	if o == nil || IsNil(o.TeamType) {
		var ret string
		return ret
	}
	return *o.TeamType
}

// GetTeamTypeOk returns a tuple with the TeamType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTeamByIdV2200Response) GetTeamTypeOk() (*string, bool) {
	if o == nil || IsNil(o.TeamType) {
		return nil, false
	}
	return o.TeamType, true
}

// HasTeamType returns a boolean if a field has been set.
func (o *GetTeamByIdV2200Response) HasTeamType() bool {
	if o != nil && !IsNil(o.TeamType) {
		return true
	}

	return false
}

// SetTeamType gets a reference to the given string and assigns it to the TeamType field.
func (o *GetTeamByIdV2200Response) SetTeamType(v string) {
	o.TeamType = &v
}

// GetTeamMembersCount returns the TeamMembersCount field value if set, zero value otherwise.
func (o *GetTeamByIdV2200Response) GetTeamMembersCount() int32 {
	if o == nil || IsNil(o.TeamMembersCount) {
		var ret int32
		return ret
	}
	return *o.TeamMembersCount
}

// GetTeamMembersCountOk returns a tuple with the TeamMembersCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTeamByIdV2200Response) GetTeamMembersCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TeamMembersCount) {
		return nil, false
	}
	return o.TeamMembersCount, true
}

// HasTeamMembersCount returns a boolean if a field has been set.
func (o *GetTeamByIdV2200Response) HasTeamMembersCount() bool {
	if o != nil && !IsNil(o.TeamMembersCount) {
		return true
	}

	return false
}

// SetTeamMembersCount gets a reference to the given int32 and assigns it to the TeamMembersCount field.
func (o *GetTeamByIdV2200Response) SetTeamMembersCount(v int32) {
	o.TeamMembersCount = &v
}

// GetTeamReleaseGroupsCount returns the TeamReleaseGroupsCount field value if set, zero value otherwise.
func (o *GetTeamByIdV2200Response) GetTeamReleaseGroupsCount() int32 {
	if o == nil || IsNil(o.TeamReleaseGroupsCount) {
		var ret int32
		return ret
	}
	return *o.TeamReleaseGroupsCount
}

// GetTeamReleaseGroupsCountOk returns a tuple with the TeamReleaseGroupsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTeamByIdV2200Response) GetTeamReleaseGroupsCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TeamReleaseGroupsCount) {
		return nil, false
	}
	return o.TeamReleaseGroupsCount, true
}

// HasTeamReleaseGroupsCount returns a boolean if a field has been set.
func (o *GetTeamByIdV2200Response) HasTeamReleaseGroupsCount() bool {
	if o != nil && !IsNil(o.TeamReleaseGroupsCount) {
		return true
	}

	return false
}

// SetTeamReleaseGroupsCount gets a reference to the given int32 and assigns it to the TeamReleaseGroupsCount field.
func (o *GetTeamByIdV2200Response) SetTeamReleaseGroupsCount(v int32) {
	o.TeamReleaseGroupsCount = &v
}

// GetTeamProjectsCount returns the TeamProjectsCount field value if set, zero value otherwise.
func (o *GetTeamByIdV2200Response) GetTeamProjectsCount() int32 {
	if o == nil || IsNil(o.TeamProjectsCount) {
		var ret int32
		return ret
	}
	return *o.TeamProjectsCount
}

// GetTeamProjectsCountOk returns a tuple with the TeamProjectsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTeamByIdV2200Response) GetTeamProjectsCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TeamProjectsCount) {
		return nil, false
	}
	return o.TeamProjectsCount, true
}

// HasTeamProjectsCount returns a boolean if a field has been set.
func (o *GetTeamByIdV2200Response) HasTeamProjectsCount() bool {
	if o != nil && !IsNil(o.TeamProjectsCount) {
		return true
	}

	return false
}

// SetTeamProjectsCount gets a reference to the given int32 and assigns it to the TeamProjectsCount field.
func (o *GetTeamByIdV2200Response) SetTeamProjectsCount(v int32) {
	o.TeamProjectsCount = &v
}

// GetTeamOIDCProvidersCount returns the TeamOIDCProvidersCount field value if set, zero value otherwise.
func (o *GetTeamByIdV2200Response) GetTeamOIDCProvidersCount() int32 {
	if o == nil || IsNil(o.TeamOIDCProvidersCount) {
		var ret int32
		return ret
	}
	return *o.TeamOIDCProvidersCount
}

// GetTeamOIDCProvidersCountOk returns a tuple with the TeamOIDCProvidersCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTeamByIdV2200Response) GetTeamOIDCProvidersCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TeamOIDCProvidersCount) {
		return nil, false
	}
	return o.TeamOIDCProvidersCount, true
}

// HasTeamOIDCProvidersCount returns a boolean if a field has been set.
func (o *GetTeamByIdV2200Response) HasTeamOIDCProvidersCount() bool {
	if o != nil && !IsNil(o.TeamOIDCProvidersCount) {
		return true
	}

	return false
}

// SetTeamOIDCProvidersCount gets a reference to the given int32 and assigns it to the TeamOIDCProvidersCount field.
func (o *GetTeamByIdV2200Response) SetTeamOIDCProvidersCount(v int32) {
	o.TeamOIDCProvidersCount = &v
}

func (o GetTeamByIdV2200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTeamByIdV2200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.OrganizationId) {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.DefaultRoleId) {
		toSerialize["defaultRoleId"] = o.DefaultRoleId
	}
	if !IsNil(o.AutoAddUsers) {
		toSerialize["autoAddUsers"] = o.AutoAddUsers
	}
	if !IsNil(o.UniqueIdentifier) {
		toSerialize["uniqueIdentifier"] = o.UniqueIdentifier
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.TeamType) {
		toSerialize["teamType"] = o.TeamType
	}
	if !IsNil(o.TeamMembersCount) {
		toSerialize["teamMembersCount"] = o.TeamMembersCount
	}
	if !IsNil(o.TeamReleaseGroupsCount) {
		toSerialize["teamReleaseGroupsCount"] = o.TeamReleaseGroupsCount
	}
	if !IsNil(o.TeamProjectsCount) {
		toSerialize["teamProjectsCount"] = o.TeamProjectsCount
	}
	if !IsNil(o.TeamOIDCProvidersCount) {
		toSerialize["teamOIDCProvidersCount"] = o.TeamOIDCProvidersCount
	}
	return toSerialize, nil
}

type NullableGetTeamByIdV2200Response struct {
	value *GetTeamByIdV2200Response
	isSet bool
}

func (v NullableGetTeamByIdV2200Response) Get() *GetTeamByIdV2200Response {
	return v.value
}

func (v *NullableGetTeamByIdV2200Response) Set(val *GetTeamByIdV2200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTeamByIdV2200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTeamByIdV2200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTeamByIdV2200Response(val *GetTeamByIdV2200Response) *NullableGetTeamByIdV2200Response {
	return &NullableGetTeamByIdV2200Response{value: val, isSet: true}
}

func (v NullableGetTeamByIdV2200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTeamByIdV2200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


