/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ExchangeOIDCToken200ResponseCredential type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExchangeOIDCToken200ResponseCredential{}

// ExchangeOIDCToken200ResponseCredential The FOSSA credential information
type ExchangeOIDCToken200ResponseCredential struct {
	// The FOSSA token that can be used to authenticate with the FOSSA API
	Token string `json:"token"`
	// Whether the FOSSA token is push-only
	IsPushOnly bool `json:"isPushOnly"`
	// When the FOSSA token expires
	Expiration time.Time `json:"expiration"`
}

type _ExchangeOIDCToken200ResponseCredential ExchangeOIDCToken200ResponseCredential

// NewExchangeOIDCToken200ResponseCredential instantiates a new ExchangeOIDCToken200ResponseCredential object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExchangeOIDCToken200ResponseCredential(token string, isPushOnly bool, expiration time.Time) *ExchangeOIDCToken200ResponseCredential {
	this := ExchangeOIDCToken200ResponseCredential{}
	this.Token = token
	this.IsPushOnly = isPushOnly
	this.Expiration = expiration
	return &this
}

// NewExchangeOIDCToken200ResponseCredentialWithDefaults instantiates a new ExchangeOIDCToken200ResponseCredential object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExchangeOIDCToken200ResponseCredentialWithDefaults() *ExchangeOIDCToken200ResponseCredential {
	this := ExchangeOIDCToken200ResponseCredential{}
	return &this
}

// GetToken returns the Token field value
func (o *ExchangeOIDCToken200ResponseCredential) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *ExchangeOIDCToken200ResponseCredential) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *ExchangeOIDCToken200ResponseCredential) SetToken(v string) {
	o.Token = v
}

// GetIsPushOnly returns the IsPushOnly field value
func (o *ExchangeOIDCToken200ResponseCredential) GetIsPushOnly() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsPushOnly
}

// GetIsPushOnlyOk returns a tuple with the IsPushOnly field value
// and a boolean to check if the value has been set.
func (o *ExchangeOIDCToken200ResponseCredential) GetIsPushOnlyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsPushOnly, true
}

// SetIsPushOnly sets field value
func (o *ExchangeOIDCToken200ResponseCredential) SetIsPushOnly(v bool) {
	o.IsPushOnly = v
}

// GetExpiration returns the Expiration field value
func (o *ExchangeOIDCToken200ResponseCredential) GetExpiration() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Expiration
}

// GetExpirationOk returns a tuple with the Expiration field value
// and a boolean to check if the value has been set.
func (o *ExchangeOIDCToken200ResponseCredential) GetExpirationOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expiration, true
}

// SetExpiration sets field value
func (o *ExchangeOIDCToken200ResponseCredential) SetExpiration(v time.Time) {
	o.Expiration = v
}

func (o ExchangeOIDCToken200ResponseCredential) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExchangeOIDCToken200ResponseCredential) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	toSerialize["isPushOnly"] = o.IsPushOnly
	toSerialize["expiration"] = o.Expiration
	return toSerialize, nil
}

func (o *ExchangeOIDCToken200ResponseCredential) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
		"isPushOnly",
		"expiration",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExchangeOIDCToken200ResponseCredential := _ExchangeOIDCToken200ResponseCredential{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExchangeOIDCToken200ResponseCredential)

	if err != nil {
		return err
	}

	*o = ExchangeOIDCToken200ResponseCredential(varExchangeOIDCToken200ResponseCredential)

	return err
}

type NullableExchangeOIDCToken200ResponseCredential struct {
	value *ExchangeOIDCToken200ResponseCredential
	isSet bool
}

func (v NullableExchangeOIDCToken200ResponseCredential) Get() *ExchangeOIDCToken200ResponseCredential {
	return v.value
}

func (v *NullableExchangeOIDCToken200ResponseCredential) Set(val *ExchangeOIDCToken200ResponseCredential) {
	v.value = val
	v.isSet = true
}

func (v NullableExchangeOIDCToken200ResponseCredential) IsSet() bool {
	return v.isSet
}

func (v *NullableExchangeOIDCToken200ResponseCredential) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExchangeOIDCToken200ResponseCredential(val *ExchangeOIDCToken200ResponseCredential) *NullableExchangeOIDCToken200ResponseCredential {
	return &NullableExchangeOIDCToken200ResponseCredential{value: val, isSet: true}
}

func (v NullableExchangeOIDCToken200ResponseCredential) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExchangeOIDCToken200ResponseCredential) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


