/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the PatchJiraConfigurationRequestComponentsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchJiraConfigurationRequestComponentsInner{}

// PatchJiraConfigurationRequestComponentsInner struct for PatchJiraConfigurationRequestComponentsInner
type PatchJiraConfigurationRequestComponentsInner struct {
	// The corresponding component ID in the Jira site
	Id *string `json:"id,omitempty"`
	// Display name of the component as shown in FOSSA
	DisplayName *string `json:"displayName,omitempty"`
}

// NewPatchJiraConfigurationRequestComponentsInner instantiates a new PatchJiraConfigurationRequestComponentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchJiraConfigurationRequestComponentsInner() *PatchJiraConfigurationRequestComponentsInner {
	this := PatchJiraConfigurationRequestComponentsInner{}
	return &this
}

// NewPatchJiraConfigurationRequestComponentsInnerWithDefaults instantiates a new PatchJiraConfigurationRequestComponentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchJiraConfigurationRequestComponentsInnerWithDefaults() *PatchJiraConfigurationRequestComponentsInner {
	this := PatchJiraConfigurationRequestComponentsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PatchJiraConfigurationRequestComponentsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchJiraConfigurationRequestComponentsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PatchJiraConfigurationRequestComponentsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PatchJiraConfigurationRequestComponentsInner) SetId(v string) {
	o.Id = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *PatchJiraConfigurationRequestComponentsInner) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchJiraConfigurationRequestComponentsInner) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *PatchJiraConfigurationRequestComponentsInner) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *PatchJiraConfigurationRequestComponentsInner) SetDisplayName(v string) {
	o.DisplayName = &v
}

func (o PatchJiraConfigurationRequestComponentsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchJiraConfigurationRequestComponentsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	return toSerialize, nil
}

type NullablePatchJiraConfigurationRequestComponentsInner struct {
	value *PatchJiraConfigurationRequestComponentsInner
	isSet bool
}

func (v NullablePatchJiraConfigurationRequestComponentsInner) Get() *PatchJiraConfigurationRequestComponentsInner {
	return v.value
}

func (v *NullablePatchJiraConfigurationRequestComponentsInner) Set(val *PatchJiraConfigurationRequestComponentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchJiraConfigurationRequestComponentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchJiraConfigurationRequestComponentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchJiraConfigurationRequestComponentsInner(val *PatchJiraConfigurationRequestComponentsInner) *NullablePatchJiraConfigurationRequestComponentsInner {
	return &NullablePatchJiraConfigurationRequestComponentsInner{value: val, isSet: true}
}

func (v NullablePatchJiraConfigurationRequestComponentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchJiraConfigurationRequestComponentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


