/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the GetTeamGroupById200ResponseMembersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTeamGroupById200ResponseMembersInner{}

// GetTeamGroupById200ResponseMembersInner struct for GetTeamGroupById200ResponseMembersInner
type GetTeamGroupById200ResponseMembersInner struct {
	// User ID
	UserId *int32 `json:"userId,omitempty"`
	// Role ID
	RoleId *int32 `json:"roleId,omitempty"`
	// Username
	Username *string `json:"username,omitempty"`
	// Email address
	Email *string `json:"email,omitempty"`
}

// NewGetTeamGroupById200ResponseMembersInner instantiates a new GetTeamGroupById200ResponseMembersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTeamGroupById200ResponseMembersInner() *GetTeamGroupById200ResponseMembersInner {
	this := GetTeamGroupById200ResponseMembersInner{}
	return &this
}

// NewGetTeamGroupById200ResponseMembersInnerWithDefaults instantiates a new GetTeamGroupById200ResponseMembersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTeamGroupById200ResponseMembersInnerWithDefaults() *GetTeamGroupById200ResponseMembersInner {
	this := GetTeamGroupById200ResponseMembersInner{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *GetTeamGroupById200ResponseMembersInner) GetUserId() int32 {
	if o == nil || IsNil(o.UserId) {
		var ret int32
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTeamGroupById200ResponseMembersInner) GetUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *GetTeamGroupById200ResponseMembersInner) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given int32 and assigns it to the UserId field.
func (o *GetTeamGroupById200ResponseMembersInner) SetUserId(v int32) {
	o.UserId = &v
}

// GetRoleId returns the RoleId field value if set, zero value otherwise.
func (o *GetTeamGroupById200ResponseMembersInner) GetRoleId() int32 {
	if o == nil || IsNil(o.RoleId) {
		var ret int32
		return ret
	}
	return *o.RoleId
}

// GetRoleIdOk returns a tuple with the RoleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTeamGroupById200ResponseMembersInner) GetRoleIdOk() (*int32, bool) {
	if o == nil || IsNil(o.RoleId) {
		return nil, false
	}
	return o.RoleId, true
}

// HasRoleId returns a boolean if a field has been set.
func (o *GetTeamGroupById200ResponseMembersInner) HasRoleId() bool {
	if o != nil && !IsNil(o.RoleId) {
		return true
	}

	return false
}

// SetRoleId gets a reference to the given int32 and assigns it to the RoleId field.
func (o *GetTeamGroupById200ResponseMembersInner) SetRoleId(v int32) {
	o.RoleId = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *GetTeamGroupById200ResponseMembersInner) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTeamGroupById200ResponseMembersInner) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *GetTeamGroupById200ResponseMembersInner) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *GetTeamGroupById200ResponseMembersInner) SetUsername(v string) {
	o.Username = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *GetTeamGroupById200ResponseMembersInner) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTeamGroupById200ResponseMembersInner) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *GetTeamGroupById200ResponseMembersInner) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *GetTeamGroupById200ResponseMembersInner) SetEmail(v string) {
	o.Email = &v
}

func (o GetTeamGroupById200ResponseMembersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTeamGroupById200ResponseMembersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	if !IsNil(o.RoleId) {
		toSerialize["roleId"] = o.RoleId
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	return toSerialize, nil
}

type NullableGetTeamGroupById200ResponseMembersInner struct {
	value *GetTeamGroupById200ResponseMembersInner
	isSet bool
}

func (v NullableGetTeamGroupById200ResponseMembersInner) Get() *GetTeamGroupById200ResponseMembersInner {
	return v.value
}

func (v *NullableGetTeamGroupById200ResponseMembersInner) Set(val *GetTeamGroupById200ResponseMembersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTeamGroupById200ResponseMembersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTeamGroupById200ResponseMembersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTeamGroupById200ResponseMembersInner(val *GetTeamGroupById200ResponseMembersInner) *NullableGetTeamGroupById200ResponseMembersInner {
	return &NullableGetTeamGroupById200ResponseMembersInner{value: val, isSet: true}
}

func (v NullableGetTeamGroupById200ResponseMembersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTeamGroupById200ResponseMembersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


