/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
	"time"
)

// checks if the GetIssueCounts200ResponseCountsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetIssueCounts200ResponseCountsInner{}

// GetIssueCounts200ResponseCountsInner struct for GetIssueCounts200ResponseCountsInner
type GetIssueCounts200ResponseCountsInner struct {
	Date *time.Time `json:"date,omitempty"`
	Active *int32 `json:"active,omitempty"`
	Ignored *int32 `json:"ignored,omitempty"`
	Remediated *int32 `json:"remediated,omitempty"`
}

// NewGetIssueCounts200ResponseCountsInner instantiates a new GetIssueCounts200ResponseCountsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIssueCounts200ResponseCountsInner() *GetIssueCounts200ResponseCountsInner {
	this := GetIssueCounts200ResponseCountsInner{}
	return &this
}

// NewGetIssueCounts200ResponseCountsInnerWithDefaults instantiates a new GetIssueCounts200ResponseCountsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIssueCounts200ResponseCountsInnerWithDefaults() *GetIssueCounts200ResponseCountsInner {
	this := GetIssueCounts200ResponseCountsInner{}
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *GetIssueCounts200ResponseCountsInner) GetDate() time.Time {
	if o == nil || IsNil(o.Date) {
		var ret time.Time
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssueCounts200ResponseCountsInner) GetDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *GetIssueCounts200ResponseCountsInner) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given time.Time and assigns it to the Date field.
func (o *GetIssueCounts200ResponseCountsInner) SetDate(v time.Time) {
	o.Date = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *GetIssueCounts200ResponseCountsInner) GetActive() int32 {
	if o == nil || IsNil(o.Active) {
		var ret int32
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssueCounts200ResponseCountsInner) GetActiveOk() (*int32, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *GetIssueCounts200ResponseCountsInner) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given int32 and assigns it to the Active field.
func (o *GetIssueCounts200ResponseCountsInner) SetActive(v int32) {
	o.Active = &v
}

// GetIgnored returns the Ignored field value if set, zero value otherwise.
func (o *GetIssueCounts200ResponseCountsInner) GetIgnored() int32 {
	if o == nil || IsNil(o.Ignored) {
		var ret int32
		return ret
	}
	return *o.Ignored
}

// GetIgnoredOk returns a tuple with the Ignored field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssueCounts200ResponseCountsInner) GetIgnoredOk() (*int32, bool) {
	if o == nil || IsNil(o.Ignored) {
		return nil, false
	}
	return o.Ignored, true
}

// HasIgnored returns a boolean if a field has been set.
func (o *GetIssueCounts200ResponseCountsInner) HasIgnored() bool {
	if o != nil && !IsNil(o.Ignored) {
		return true
	}

	return false
}

// SetIgnored gets a reference to the given int32 and assigns it to the Ignored field.
func (o *GetIssueCounts200ResponseCountsInner) SetIgnored(v int32) {
	o.Ignored = &v
}

// GetRemediated returns the Remediated field value if set, zero value otherwise.
func (o *GetIssueCounts200ResponseCountsInner) GetRemediated() int32 {
	if o == nil || IsNil(o.Remediated) {
		var ret int32
		return ret
	}
	return *o.Remediated
}

// GetRemediatedOk returns a tuple with the Remediated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssueCounts200ResponseCountsInner) GetRemediatedOk() (*int32, bool) {
	if o == nil || IsNil(o.Remediated) {
		return nil, false
	}
	return o.Remediated, true
}

// HasRemediated returns a boolean if a field has been set.
func (o *GetIssueCounts200ResponseCountsInner) HasRemediated() bool {
	if o != nil && !IsNil(o.Remediated) {
		return true
	}

	return false
}

// SetRemediated gets a reference to the given int32 and assigns it to the Remediated field.
func (o *GetIssueCounts200ResponseCountsInner) SetRemediated(v int32) {
	o.Remediated = &v
}

func (o GetIssueCounts200ResponseCountsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetIssueCounts200ResponseCountsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Ignored) {
		toSerialize["ignored"] = o.Ignored
	}
	if !IsNil(o.Remediated) {
		toSerialize["remediated"] = o.Remediated
	}
	return toSerialize, nil
}

type NullableGetIssueCounts200ResponseCountsInner struct {
	value *GetIssueCounts200ResponseCountsInner
	isSet bool
}

func (v NullableGetIssueCounts200ResponseCountsInner) Get() *GetIssueCounts200ResponseCountsInner {
	return v.value
}

func (v *NullableGetIssueCounts200ResponseCountsInner) Set(val *GetIssueCounts200ResponseCountsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIssueCounts200ResponseCountsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIssueCounts200ResponseCountsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIssueCounts200ResponseCountsInner(val *GetIssueCounts200ResponseCountsInner) *NullableGetIssueCounts200ResponseCountsInner {
	return &NullableGetIssueCounts200ResponseCountsInner{value: val, isSet: true}
}

func (v NullableGetIssueCounts200ResponseCountsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIssueCounts200ResponseCountsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


