/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner{}

// GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner struct for GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner
type GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner struct {
	IssueId *int32 `json:"issueId,omitempty"`
	ProjectId *string `json:"projectId,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewGetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner instantiates a new GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner() *GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner {
	this := GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner{}
	return &this
}

// NewGetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInnerWithDefaults instantiates a new GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInnerWithDefaults() *GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner {
	this := GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner{}
	return &this
}

// GetIssueId returns the IssueId field value if set, zero value otherwise.
func (o *GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) GetIssueId() int32 {
	if o == nil || IsNil(o.IssueId) {
		var ret int32
		return ret
	}
	return *o.IssueId
}

// GetIssueIdOk returns a tuple with the IssueId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) GetIssueIdOk() (*int32, bool) {
	if o == nil || IsNil(o.IssueId) {
		return nil, false
	}
	return o.IssueId, true
}

// HasIssueId returns a boolean if a field has been set.
func (o *GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) HasIssueId() bool {
	if o != nil && !IsNil(o.IssueId) {
		return true
	}

	return false
}

// SetIssueId gets a reference to the given int32 and assigns it to the IssueId field.
func (o *GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) SetIssueId(v int32) {
	o.IssueId = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) SetStatus(v string) {
	o.Status = &v
}

func (o GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IssueId) {
		toSerialize["issueId"] = o.IssueId
	}
	if !IsNil(o.ProjectId) {
		toSerialize["projectId"] = o.ProjectId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableGetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner struct {
	value *GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner
	isSet bool
}

func (v NullableGetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) Get() *GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner {
	return v.value
}

func (v *NullableGetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) Set(val *GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner(val *GetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) *NullableGetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner {
	return &NullableGetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner{value: val, isSet: true}
}

func (v NullableGetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRevisionDependenciesPost200ResponseInnerIssueTargetsInnerParentContextsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


