/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the GetOrganizationPipSettings200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrganizationPipSettings200Response{}

// GetOrganizationPipSettings200Response struct for GetOrganizationPipSettings200Response
type GetOrganizationPipSettings200Response struct {
	// List of configured Pip Repositories
	Repositories []GetOrganizationPipSettings200ResponseRepositoriesInner `json:"repositories,omitempty"`
}

// NewGetOrganizationPipSettings200Response instantiates a new GetOrganizationPipSettings200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrganizationPipSettings200Response() *GetOrganizationPipSettings200Response {
	this := GetOrganizationPipSettings200Response{}
	return &this
}

// NewGetOrganizationPipSettings200ResponseWithDefaults instantiates a new GetOrganizationPipSettings200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrganizationPipSettings200ResponseWithDefaults() *GetOrganizationPipSettings200Response {
	this := GetOrganizationPipSettings200Response{}
	return &this
}

// GetRepositories returns the Repositories field value if set, zero value otherwise.
func (o *GetOrganizationPipSettings200Response) GetRepositories() []GetOrganizationPipSettings200ResponseRepositoriesInner {
	if o == nil || IsNil(o.Repositories) {
		var ret []GetOrganizationPipSettings200ResponseRepositoriesInner
		return ret
	}
	return o.Repositories
}

// GetRepositoriesOk returns a tuple with the Repositories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationPipSettings200Response) GetRepositoriesOk() ([]GetOrganizationPipSettings200ResponseRepositoriesInner, bool) {
	if o == nil || IsNil(o.Repositories) {
		return nil, false
	}
	return o.Repositories, true
}

// HasRepositories returns a boolean if a field has been set.
func (o *GetOrganizationPipSettings200Response) HasRepositories() bool {
	if o != nil && !IsNil(o.Repositories) {
		return true
	}

	return false
}

// SetRepositories gets a reference to the given []GetOrganizationPipSettings200ResponseRepositoriesInner and assigns it to the Repositories field.
func (o *GetOrganizationPipSettings200Response) SetRepositories(v []GetOrganizationPipSettings200ResponseRepositoriesInner) {
	o.Repositories = v
}

func (o GetOrganizationPipSettings200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrganizationPipSettings200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Repositories) {
		toSerialize["repositories"] = o.Repositories
	}
	return toSerialize, nil
}

type NullableGetOrganizationPipSettings200Response struct {
	value *GetOrganizationPipSettings200Response
	isSet bool
}

func (v NullableGetOrganizationPipSettings200Response) Get() *GetOrganizationPipSettings200Response {
	return v.value
}

func (v *NullableGetOrganizationPipSettings200Response) Set(val *GetOrganizationPipSettings200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrganizationPipSettings200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrganizationPipSettings200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrganizationPipSettings200Response(val *GetOrganizationPipSettings200Response) *NullableGetOrganizationPipSettings200Response {
	return &NullableGetOrganizationPipSettings200Response{value: val, isSet: true}
}

func (v NullableGetOrganizationPipSettings200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrganizationPipSettings200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


