/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the GetIssueDiffComparisonSummaries200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetIssueDiffComparisonSummaries200Response{}

// GetIssueDiffComparisonSummaries200Response struct for GetIssueDiffComparisonSummaries200Response
type GetIssueDiffComparisonSummaries200Response struct {
	Issues *GetIssueDiffComparisonSummaries200ResponseIssues `json:"issues,omitempty"`
	Revisions *GetIssueDiffComparisonSummaries200ResponseIssues `json:"revisions,omitempty"`
}

// NewGetIssueDiffComparisonSummaries200Response instantiates a new GetIssueDiffComparisonSummaries200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIssueDiffComparisonSummaries200Response() *GetIssueDiffComparisonSummaries200Response {
	this := GetIssueDiffComparisonSummaries200Response{}
	return &this
}

// NewGetIssueDiffComparisonSummaries200ResponseWithDefaults instantiates a new GetIssueDiffComparisonSummaries200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIssueDiffComparisonSummaries200ResponseWithDefaults() *GetIssueDiffComparisonSummaries200Response {
	this := GetIssueDiffComparisonSummaries200Response{}
	return &this
}

// GetIssues returns the Issues field value if set, zero value otherwise.
func (o *GetIssueDiffComparisonSummaries200Response) GetIssues() GetIssueDiffComparisonSummaries200ResponseIssues {
	if o == nil || IsNil(o.Issues) {
		var ret GetIssueDiffComparisonSummaries200ResponseIssues
		return ret
	}
	return *o.Issues
}

// GetIssuesOk returns a tuple with the Issues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssueDiffComparisonSummaries200Response) GetIssuesOk() (*GetIssueDiffComparisonSummaries200ResponseIssues, bool) {
	if o == nil || IsNil(o.Issues) {
		return nil, false
	}
	return o.Issues, true
}

// HasIssues returns a boolean if a field has been set.
func (o *GetIssueDiffComparisonSummaries200Response) HasIssues() bool {
	if o != nil && !IsNil(o.Issues) {
		return true
	}

	return false
}

// SetIssues gets a reference to the given GetIssueDiffComparisonSummaries200ResponseIssues and assigns it to the Issues field.
func (o *GetIssueDiffComparisonSummaries200Response) SetIssues(v GetIssueDiffComparisonSummaries200ResponseIssues) {
	o.Issues = &v
}

// GetRevisions returns the Revisions field value if set, zero value otherwise.
func (o *GetIssueDiffComparisonSummaries200Response) GetRevisions() GetIssueDiffComparisonSummaries200ResponseIssues {
	if o == nil || IsNil(o.Revisions) {
		var ret GetIssueDiffComparisonSummaries200ResponseIssues
		return ret
	}
	return *o.Revisions
}

// GetRevisionsOk returns a tuple with the Revisions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssueDiffComparisonSummaries200Response) GetRevisionsOk() (*GetIssueDiffComparisonSummaries200ResponseIssues, bool) {
	if o == nil || IsNil(o.Revisions) {
		return nil, false
	}
	return o.Revisions, true
}

// HasRevisions returns a boolean if a field has been set.
func (o *GetIssueDiffComparisonSummaries200Response) HasRevisions() bool {
	if o != nil && !IsNil(o.Revisions) {
		return true
	}

	return false
}

// SetRevisions gets a reference to the given GetIssueDiffComparisonSummaries200ResponseIssues and assigns it to the Revisions field.
func (o *GetIssueDiffComparisonSummaries200Response) SetRevisions(v GetIssueDiffComparisonSummaries200ResponseIssues) {
	o.Revisions = &v
}

func (o GetIssueDiffComparisonSummaries200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetIssueDiffComparisonSummaries200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Issues) {
		toSerialize["issues"] = o.Issues
	}
	if !IsNil(o.Revisions) {
		toSerialize["revisions"] = o.Revisions
	}
	return toSerialize, nil
}

type NullableGetIssueDiffComparisonSummaries200Response struct {
	value *GetIssueDiffComparisonSummaries200Response
	isSet bool
}

func (v NullableGetIssueDiffComparisonSummaries200Response) Get() *GetIssueDiffComparisonSummaries200Response {
	return v.value
}

func (v *NullableGetIssueDiffComparisonSummaries200Response) Set(val *GetIssueDiffComparisonSummaries200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIssueDiffComparisonSummaries200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIssueDiffComparisonSummaries200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIssueDiffComparisonSummaries200Response(val *GetIssueDiffComparisonSummaries200Response) *NullableGetIssueDiffComparisonSummaries200Response {
	return &NullableGetIssueDiffComparisonSummaries200Response{value: val, isSet: true}
}

func (v NullableGetIssueDiffComparisonSummaries200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIssueDiffComparisonSummaries200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


