/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddTeamsToTeamGroupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddTeamsToTeamGroupRequest{}

// AddTeamsToTeamGroupRequest struct for AddTeamsToTeamGroupRequest
type AddTeamsToTeamGroupRequest struct {
	// Array of team IDs to add to the team group
	TeamIds []int32 `json:"teamIds"`
}

type _AddTeamsToTeamGroupRequest AddTeamsToTeamGroupRequest

// NewAddTeamsToTeamGroupRequest instantiates a new AddTeamsToTeamGroupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddTeamsToTeamGroupRequest(teamIds []int32) *AddTeamsToTeamGroupRequest {
	this := AddTeamsToTeamGroupRequest{}
	this.TeamIds = teamIds
	return &this
}

// NewAddTeamsToTeamGroupRequestWithDefaults instantiates a new AddTeamsToTeamGroupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddTeamsToTeamGroupRequestWithDefaults() *AddTeamsToTeamGroupRequest {
	this := AddTeamsToTeamGroupRequest{}
	return &this
}

// GetTeamIds returns the TeamIds field value
func (o *AddTeamsToTeamGroupRequest) GetTeamIds() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.TeamIds
}

// GetTeamIdsOk returns a tuple with the TeamIds field value
// and a boolean to check if the value has been set.
func (o *AddTeamsToTeamGroupRequest) GetTeamIdsOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TeamIds, true
}

// SetTeamIds sets field value
func (o *AddTeamsToTeamGroupRequest) SetTeamIds(v []int32) {
	o.TeamIds = v
}

func (o AddTeamsToTeamGroupRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddTeamsToTeamGroupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["teamIds"] = o.TeamIds
	return toSerialize, nil
}

func (o *AddTeamsToTeamGroupRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"teamIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddTeamsToTeamGroupRequest := _AddTeamsToTeamGroupRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddTeamsToTeamGroupRequest)

	if err != nil {
		return err
	}

	*o = AddTeamsToTeamGroupRequest(varAddTeamsToTeamGroupRequest)

	return err
}

type NullableAddTeamsToTeamGroupRequest struct {
	value *AddTeamsToTeamGroupRequest
	isSet bool
}

func (v NullableAddTeamsToTeamGroupRequest) Get() *AddTeamsToTeamGroupRequest {
	return v.value
}

func (v *NullableAddTeamsToTeamGroupRequest) Set(val *AddTeamsToTeamGroupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddTeamsToTeamGroupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddTeamsToTeamGroupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddTeamsToTeamGroupRequest(val *AddTeamsToTeamGroupRequest) *NullableAddTeamsToTeamGroupRequest {
	return &NullableAddTeamsToTeamGroupRequest{value: val, isSet: true}
}

func (v NullableAddTeamsToTeamGroupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddTeamsToTeamGroupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


