/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.81
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossaclient

import (
	"encoding/json"
)

// checks if the ContainerIssueSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContainerIssueSettings{}

// ContainerIssueSettings struct for ContainerIssueSettings
type ContainerIssueSettings struct {
	ProjectDefaultExcludeBaseLayerIssuesLicensing *bool `json:"projectDefaultExcludeBaseLayerIssuesLicensing,omitempty"`
	ProjectDefaultExcludeBaseLayerIssuesSecurity *bool `json:"projectDefaultExcludeBaseLayerIssuesSecurity,omitempty"`
	ProjectDefaultExcludeBaseLayerIssuesQuality *bool `json:"projectDefaultExcludeBaseLayerIssuesQuality,omitempty"`
}

// NewContainerIssueSettings instantiates a new ContainerIssueSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerIssueSettings() *ContainerIssueSettings {
	this := ContainerIssueSettings{}
	return &this
}

// NewContainerIssueSettingsWithDefaults instantiates a new ContainerIssueSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerIssueSettingsWithDefaults() *ContainerIssueSettings {
	this := ContainerIssueSettings{}
	return &this
}

// GetProjectDefaultExcludeBaseLayerIssuesLicensing returns the ProjectDefaultExcludeBaseLayerIssuesLicensing field value if set, zero value otherwise.
func (o *ContainerIssueSettings) GetProjectDefaultExcludeBaseLayerIssuesLicensing() bool {
	if o == nil || IsNil(o.ProjectDefaultExcludeBaseLayerIssuesLicensing) {
		var ret bool
		return ret
	}
	return *o.ProjectDefaultExcludeBaseLayerIssuesLicensing
}

// GetProjectDefaultExcludeBaseLayerIssuesLicensingOk returns a tuple with the ProjectDefaultExcludeBaseLayerIssuesLicensing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerIssueSettings) GetProjectDefaultExcludeBaseLayerIssuesLicensingOk() (*bool, bool) {
	if o == nil || IsNil(o.ProjectDefaultExcludeBaseLayerIssuesLicensing) {
		return nil, false
	}
	return o.ProjectDefaultExcludeBaseLayerIssuesLicensing, true
}

// HasProjectDefaultExcludeBaseLayerIssuesLicensing returns a boolean if a field has been set.
func (o *ContainerIssueSettings) HasProjectDefaultExcludeBaseLayerIssuesLicensing() bool {
	if o != nil && !IsNil(o.ProjectDefaultExcludeBaseLayerIssuesLicensing) {
		return true
	}

	return false
}

// SetProjectDefaultExcludeBaseLayerIssuesLicensing gets a reference to the given bool and assigns it to the ProjectDefaultExcludeBaseLayerIssuesLicensing field.
func (o *ContainerIssueSettings) SetProjectDefaultExcludeBaseLayerIssuesLicensing(v bool) {
	o.ProjectDefaultExcludeBaseLayerIssuesLicensing = &v
}

// GetProjectDefaultExcludeBaseLayerIssuesSecurity returns the ProjectDefaultExcludeBaseLayerIssuesSecurity field value if set, zero value otherwise.
func (o *ContainerIssueSettings) GetProjectDefaultExcludeBaseLayerIssuesSecurity() bool {
	if o == nil || IsNil(o.ProjectDefaultExcludeBaseLayerIssuesSecurity) {
		var ret bool
		return ret
	}
	return *o.ProjectDefaultExcludeBaseLayerIssuesSecurity
}

// GetProjectDefaultExcludeBaseLayerIssuesSecurityOk returns a tuple with the ProjectDefaultExcludeBaseLayerIssuesSecurity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerIssueSettings) GetProjectDefaultExcludeBaseLayerIssuesSecurityOk() (*bool, bool) {
	if o == nil || IsNil(o.ProjectDefaultExcludeBaseLayerIssuesSecurity) {
		return nil, false
	}
	return o.ProjectDefaultExcludeBaseLayerIssuesSecurity, true
}

// HasProjectDefaultExcludeBaseLayerIssuesSecurity returns a boolean if a field has been set.
func (o *ContainerIssueSettings) HasProjectDefaultExcludeBaseLayerIssuesSecurity() bool {
	if o != nil && !IsNil(o.ProjectDefaultExcludeBaseLayerIssuesSecurity) {
		return true
	}

	return false
}

// SetProjectDefaultExcludeBaseLayerIssuesSecurity gets a reference to the given bool and assigns it to the ProjectDefaultExcludeBaseLayerIssuesSecurity field.
func (o *ContainerIssueSettings) SetProjectDefaultExcludeBaseLayerIssuesSecurity(v bool) {
	o.ProjectDefaultExcludeBaseLayerIssuesSecurity = &v
}

// GetProjectDefaultExcludeBaseLayerIssuesQuality returns the ProjectDefaultExcludeBaseLayerIssuesQuality field value if set, zero value otherwise.
func (o *ContainerIssueSettings) GetProjectDefaultExcludeBaseLayerIssuesQuality() bool {
	if o == nil || IsNil(o.ProjectDefaultExcludeBaseLayerIssuesQuality) {
		var ret bool
		return ret
	}
	return *o.ProjectDefaultExcludeBaseLayerIssuesQuality
}

// GetProjectDefaultExcludeBaseLayerIssuesQualityOk returns a tuple with the ProjectDefaultExcludeBaseLayerIssuesQuality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerIssueSettings) GetProjectDefaultExcludeBaseLayerIssuesQualityOk() (*bool, bool) {
	if o == nil || IsNil(o.ProjectDefaultExcludeBaseLayerIssuesQuality) {
		return nil, false
	}
	return o.ProjectDefaultExcludeBaseLayerIssuesQuality, true
}

// HasProjectDefaultExcludeBaseLayerIssuesQuality returns a boolean if a field has been set.
func (o *ContainerIssueSettings) HasProjectDefaultExcludeBaseLayerIssuesQuality() bool {
	if o != nil && !IsNil(o.ProjectDefaultExcludeBaseLayerIssuesQuality) {
		return true
	}

	return false
}

// SetProjectDefaultExcludeBaseLayerIssuesQuality gets a reference to the given bool and assigns it to the ProjectDefaultExcludeBaseLayerIssuesQuality field.
func (o *ContainerIssueSettings) SetProjectDefaultExcludeBaseLayerIssuesQuality(v bool) {
	o.ProjectDefaultExcludeBaseLayerIssuesQuality = &v
}

func (o ContainerIssueSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContainerIssueSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjectDefaultExcludeBaseLayerIssuesLicensing) {
		toSerialize["projectDefaultExcludeBaseLayerIssuesLicensing"] = o.ProjectDefaultExcludeBaseLayerIssuesLicensing
	}
	if !IsNil(o.ProjectDefaultExcludeBaseLayerIssuesSecurity) {
		toSerialize["projectDefaultExcludeBaseLayerIssuesSecurity"] = o.ProjectDefaultExcludeBaseLayerIssuesSecurity
	}
	if !IsNil(o.ProjectDefaultExcludeBaseLayerIssuesQuality) {
		toSerialize["projectDefaultExcludeBaseLayerIssuesQuality"] = o.ProjectDefaultExcludeBaseLayerIssuesQuality
	}
	return toSerialize, nil
}

type NullableContainerIssueSettings struct {
	value *ContainerIssueSettings
	isSet bool
}

func (v NullableContainerIssueSettings) Get() *ContainerIssueSettings {
	return v.value
}

func (v *NullableContainerIssueSettings) Set(val *ContainerIssueSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerIssueSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerIssueSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerIssueSettings(val *ContainerIssueSettings) *NullableContainerIssueSettings {
	return &NullableContainerIssueSettings{value: val, isSet: true}
}

func (v NullableContainerIssueSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerIssueSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


